WatWowMap/ReactMap

client/src/components/App.js, client/src/components/Map.jsx, client/src/components/layout/Drawer.jsx, client/src/components/layout/Nav.jsx, client/src/components/layout/dialogs/Settings.jsx, client/src/components/layout/dialogs/index.js, client/src/components/pokemon/Pokemon.jsx, client/src/components/pokemon/marker.js, client/src/services/Fetch.js, client/src/services/data/config.js, client/src/services/getPokemonIcon.js, server/package.json, server/src/configs/config.example.json, server/src/configs/default.json, server/src/routes/rootRouter.js, server/src/services/updateAvailableForms.js, yarn.lock
- Users can adjust what tileserver they want
- Users can change what icons they want
- Some refactoring as well
- Add accordions to menu
=> Add Changing TileServers & Icons

package.json, server/src/index.js, src/components/App.jsx, src/components/ConfigSettings.jsx, src/components/Map.jsx, src/components/gyms/Gym.jsx, src/components/pokemon/Pokemon.jsx, src/components/pokestops/Pokestop.jsx, src/components/portals/Portal.jsx, src/components/s2Cell/S2Cell.jsx, src/components/spawnpoints/Spawnpoint.jsx, src/components/submissionCells/SubmissionCells.jsx
- use "previousData" with Apollo to maintain map markers during transition period
- add compression for reduced downloads
=> Persist Map Markers During Movement

server/src/models/Gym.js, server/src/models/Pokemon.js, server/src/services/defaultFilters/buildPokemon.js, src/components/layout/dialogs/filters/Advanced.jsx, src/components/layout/dialogs/filters/Menu.jsx, src/components/layout/drawer/WithSliders.jsx, src/components/pokemon/PokemonQuery.jsx
- Use Set with backend to reduce some duplicates
- Optimized Pokemon api by not looping over redundant items
- Changed "default" to "standard" for JS reasons
- Added tabs to see all sliders on sidebar
=> Optimize Pokemon SQL & add Tabs

server/src/configs/config.example.json, server/src/configs/default.json, server/src/db/migrations/20210407180251_discordUsers.cjs, server/src/index.js, server/src/models/Filters.js, server/src/models/Gym.js, server/src/models/Session.js, server/src/models/User.js, server/src/routes/clientRouter.js, server/src/routes/rootRouter.js, server/src/services/defaultFilters/buildDefaultFilters.js, server/src/services/defaultFilters/buildGyms.js, server/src/services/defaultFilters/buildPokemon.js, server/src/services/defaultFilters/buildQuests.js, server/src/services/discord.js, server/src/services/session-store.js, server/src/strategies/discordStrategy.js, src/assets/mui/styling.js, src/assets/mui/theme.js, src/components/ConfigSettings.jsx, src/components/Login.jsx, src/components/layout/FloatingBtn.jsx
- Cleaned up config
- Moved things that make more sense
- Initial dark mode support
- Allow customization of primary and secondary
=> Config Cleanup

server/src/configs/default.json, server/src/routes/rootRouter.js, src/components/layout/drawer/Drawer.jsx, src/components/popups/Pokemon.jsx
- Drawer can now be temporary (closes if a user taps outside of it) or persistent, stays open until the X is clicked
- Bug fixes for popup when iv is 0
=> Adds ability for drawer to be configured by user

server/src/schema/device.js, server/src/schema/schema.js, server/src/services/functions/getPolyVector.js, src/components/markers/device.js, src/components/popups/Device.jsx, src/components/popups/DevicePoly.jsx, src/components/tiles/Device.jsx, src/services/queries/device.js
- Show UUID, instance_name, last seen, and status
- Show polyline for circle_pokemon
- Show polygon for other instances
=> Add Device Popups

server/src/schema/device.js, server/src/schema/schema.js, src/components/popups/DevicePoly.jsx, src/components/popups/Pokemon.jsx, src/services/queries/device.js
- Fixes Pokemon popup for those without Pvp perms
- Fixes high cpu usage and calculates Device polylines/polygons on a per device basis
=> Bug & Performance Fixes

server/src/routes/rootRouter.js
=> Disable Introspection

package.json, server/src/models/Pokemon.js, server/src/services/ui.js, src/assets/scss/main.scss, src/components/layout/FloatingBtn.jsx, src/components/layout/dialogs/filters/Footer.jsx, src/components/layout/dialogs/filters/SliderTile.jsx, src/services/functions/filterPokemon.js, yarn.lock
- Fix PVP Filtering
- Location setting is much better now
- Add labels to some of the sliders
- Remove unnecessary advanced menus in Pokestop/Gym menus
- Fix search to include name for Pokemon that aren't the primary form
=> Various Adjustments

server/src/configs/config.example.json, server/src/configs/default.json, server/src/models/Pokemon.js, server/src/schema/portal.js, server/src/schema/schema.js, server/src/services/functions/getPolyVector.js, src/components/QueryData.jsx, src/components/layout/dialogs/filters/Footer.jsx, src/components/layout/dialogs/filters/MenuTile.jsx, src/components/markers/placementCell.js, src/components/markers/typeCell.js, src/components/markers/weather.js, src/components/popups/Gym.jsx, src/components/popups/Pokestop.jsx, src/components/popups/Portal.jsx, src/components/popups/S2cell.jsx, src/components/popups/Spawnpoint.jsx, src/components/popups/SubmissionCell.jsx, src/components/popups/Weather.jsx, src/components/tiles/Weather.jsx, src/services/functions/filterPokestops.js, src/services/queries/portal.js, src/services/queries/spawnpoint.js
Features:
- Portal Popups
- Spawnpoint Popups
- S2Cell Popups
- Submission Cell Popups
- Weather Popups
Bug Fixes:
- PVP Fixes for RDM databases
- Show red lines instead of black on darker tile sets
Probably need to clear local storage to see the red line/black line transition.
=> Other popups

server/src/configs/config.example.json, server/src/configs/default.json, server/src/routes/rootRouter.js, src/components/layout/drawer/Areas.jsx, src/components/tiles/ScanArea.jsx
- Support built in geojson style properties
- Support optional manual areas in config
- Adjustable zoom levels
=> Geojson color support & manual areas

server/src/services/legacyFilter.js
- Fix legacy filter so it's compatible with the new pvp system
=> Fix Legacy Filter

server/src/configs/config.example.json, server/src/configs/default.json, src/components/layout/FloatingBtn.jsx
- Config option to add a stats FOB
- Set link in config as well
=> Add Stats Link

public/index.html, public/index.template.html
=> Add web-app-capable meta

public/base-locales/en-us.json, public/base-locales/en.json, public/base-locales/es.json, public/base-locales/fr.json, public/base-locales/it.json, public/base-locales/jp.json, public/base-locales/pl.json
=> fix locale selector pl

README.md, server/src/models/Nest.js, server/src/routes/clientRouter.js, server/src/schema/schema.js, src/components/App.jsx, src/components/Auth.jsx, src/components/ConfigSettings.jsx, src/components/WebhookQuery.jsx, src/components/tiles/Gym.jsx, src/components/tiles/Pokemon.jsx, src/services/Query.js, src/services/queries/gym.js, src/services/queries/nest.js, src/services/queries/pokemon.js, src/services/queries/pokestop.js
- Supports Pokemon, Gyms, Pokestops, and Nests
- https://www.mymap.com/id/{category}/{id}/{zoom}
=> Adds Pkmn/Gym/Stop/Nest ID Links for webhooks

server/src/models/Pokemon.js, server/src/schema/pokemon.js, src/components/popups/Pokemon.jsx, src/services/queries/pokemon.js
- Store Ditto in new variable and give Ditto its original form to stop breaking the frontend size check
=> Fixes Ditto for Chuck

public/base-locales/en.json, server/generateMasterfile.js, server/src/routes/rootRouter.js, server/src/services/functions/fetchJson.js, server/src/services/functions/fetchNests.js, server/src/services/functions/fetchQuests.js, server/src/services/functions/fetchRaids.js, src/assets/scss/main.scss, src/components/App.jsx, src/components/ConfigSettings.jsx, src/components/Login.jsx, src/services/fetches/getSettings.js
- Masterfile
- Pogoinfo
- Available
=> Try/Catch Blocks for fetch errors

public/base-locales/en.json, server/src/configs/default.json, server/src/services/ui/clientOptions.js, src/components/Clustering.jsx, src/components/tiles/Gym.jsx, src/components/tiles/Pokemon.jsx, src/components/tiles/Pokestop.jsx
- Pokestop, Pokemon, Gyms
- Default value set in config (default.json)
- New translation line
=> Interaction Ranges

server/src/configs/default.json, server/src/services/defaultFilters/buildDefaultFilters.js, server/src/services/ui/clientOptions.js, src/components/layout/dialogs/filters/Advanced.jsx, yarn.lock
- Config option to hide it in the Pokemon Options menu as well as the advanced slider menu for individual Pokemon if you don't want your users to see it at all
=> Legacy Filter Optional

server/src/configs/config.example.json, server/src/configs/default.json, server/src/routes/rootRouter.js, server/src/services/discord.js, src/components/ConfigSettings.jsx, src/components/layout/drawer/Settings.jsx, src/hooks/useStore.js
- Can add specific categories to this array that allows users to view those categories without having to login to Discord, even when Discord is enabled.
- `false` on each perm now makes it not viewable even if there are perms in the role array
- Logout button can now be a login button if the user is not logged in
- Logout/Login button does not appear if discord is disabled
=> Adds Optional Discord Array

src/components/markers/pokemon.js, src/components/popups/Pokemon.jsx, src/components/tiles/Gym.jsx, src/components/tiles/Pokemon.jsx
- Fix hasRaid Check when displaying all timers
- Fix IV circles from being displayed on non-iv Pokemon
=> Various Bug Fixes

public/base-locales/en.json, public/base-locales/fr.json, src/components/ConfigSettings.jsx, src/components/layout/FloatingBtn.jsx
Adds title description when mouse over the menu / location / zoom buttons
=> Adds title description when mouse over the menu / location / zoom buttons

public/base-locales/en.json, server/generateMasterfile.js, server/src/configs/default.json, server/src/models/Pokestop.js, server/src/schema/pokestop.js, server/src/services/defaultFilters/buildPokemon.js, server/src/services/ui/advMenus.js, src/components/markers/pokestop.js, src/components/popups/Pokestop.jsx, src/components/tiles/Pokestop.jsx, src/services/functions/menuFilter.js, src/services/functions/parseConditions.js, src/services/queries/pokestop.js
- Checks available quests in db
- Generates filters with only the base form
- Candy + Pokemon markers
- Candy translation
- ~~Needs MAD testing still~~
=> Candy Support

server/src/models/Gym.js, src/components/popups/Gym.jsx
- Cleanup popup code
- Restores unknown eggs from disappearing
=> Fix unknown eggs from not appearing

src/components/layout/dialogs/filters/Menu.jsx, src/components/layout/drawer/Drawer.jsx, src/hooks/useStore.js
- Now keeps the last accordion that the user opened, open upon page refresh/closing of the menu
=> Persist Menu Selections

src/components/layout/dialogs/filters/Advanced.jsx, src/components/layout/dialogs/filters/SliderTile.jsx, src/components/layout/drawer/WithSliders.jsx
- Can now have a blank value in the text box
- No more errors or warnings
=> Sliders Work More Consistently

src/components/layout/FloatingBtn.jsx
=> Fix location following

src/components/popups/Pokestop.jsx, src/components/tiles/Pokestop.jsx
- Removes double flash when excluding mega energy
- Fixes excluding a candy based quest
=> Fix Quest Excluding

server/src/models/Gym.js, src/components/layout/dialogs/Search.jsx
- Check if raid has expired
- Add default unknown names if poi is not named
=> Search Fixes

src/hooks/useStyles.js
=> Add styling to the scrollbar

src/components/popups/Pokemon.jsx
Removing misleading `cap=50` when it also applies to cap 51.
=> Do not show cap if entry is capped

src/components/layout/FloatingBtn.jsx
tested so plz merge okthx
*I am slowly becoming a React expert thanks to you*
=> Fix dom events propagating through Fabs

server/src/models/Pokemon.js, server/src/schema/schema.js, server/src/services/legacyFilter.js, src/services/functions/checkAdvFilter.js, yarn.lock
- MapJS Legacy Filter now supports Little Cup/Ohbem
- Legacy Filter now supports MAD
=> Fixes MAD Legacy Filter

src/components/popups/Spawnpoint.jsx
=> Rework spawnpoint style

src/components/layout/FloatingBtn.jsx
Reverts WatWowMap/ReactMap#128
Causes more issues than it fixes, reverting for now.
=> Revert "Fix dom events propagating through Fabs"

src/components/popups/DevicePoly.jsx
=> Fix Multi Polygon Routes

server/src/configs/default.json, src/components/App.jsx, src/services/Icons.js
- adds option to specify a mix of styles as default:
```
"defaultIcons": {
"raid": "PMSF",
"pokemon": "Home"
}
```
=> Add defaultIcons

public/base-locales/en.json, server/src/models/Gym.js, server/src/models/Pokemon.js, server/src/models/Pokestop.js, server/src/routes/rootRouter.js, server/src/services/createLocales.js, server/src/services/generateMasterfile.js, src/components/Auth.jsx, src/components/ConfigSettings.jsx, src/components/layout/dialogs/filters/Menu.jsx, src/services/functions/menuFilter.js
- Now Supports Unset Quest Rewards, in addition to set
- Move Default to end of Switch functions
- Filter out "onlyX" in Pokestop Model
- Match Pokestop Model style with Gym Model
- Add empty array of types for Masterfile Pokemon as a backup if missing
=> Support Both Set & Unset Quest Pokemon Rewards

src/components/layout/FloatingBtn.jsx, src/components/layout/drawer/Settings.jsx
- Rehash of #128
- Now has a set width to avoid the issues from last time
=> Rehash of Fix Dom Events Propagating through Fabs

server/src/routes/rootRouter.js
- Fixes error during startup if missing perms
=> Filter Check Fix

package.json, server/src/strategies/discordStrategy.js
=> Remove Axios

public/base-locales/de.json
I think "PVP Stats" is also valid for german.
=> Filter by Caps & Mega - Update de.json

public/base-locales/de.json, public/base-locales/en.json, public/base-locales/fr.json, public/base-locales/pl.json, server/src/configs/default.json, server/src/models/Pokemon.js, server/src/services/legacyFilter.js, server/src/services/ui/clientOptions.js, src/components/QueryData.jsx, src/components/layout/dialogs/UserOptions.jsx, src/components/layout/drawer/WithSliders.jsx, src/components/layout/general/TabPanel.jsx
- Adds a couple of locale keys
- Adds a second tab for the Pokemon option menu
- Filter by different level caps for PVP
- Filter PVP results by Megas
- Dynamically adjusts for any number of level caps specified in the config
Addresses #168
=> Filter by Caps & Mega

src/components/popups/Pokestop.jsx, src/services/functions/parseConditions.js
- Alignment quest was improperly keyed
=> Fix Alignment Quest

src/components/markers/gym.jsx
=> Consistify Raid Modifiers

src/components/layout/dialogs/filters/Menu.jsx
- Enable All/Disable All now affect the gym slot sub menus as well for a better user experience
=> Fix Adv Gym Slots

server/src/routes/authRouter.js, server/src/routes/clientRouter.js, server/src/routes/rootRouter.js, src/components/App.jsx
- Adds backend area/city support that redirects to the center lat/lon
- Also makes zoom an optional param on the other routes
- /area/:area/:zoom?
=> Add Area/City Route Support

public/base-locales/en.json, src/components/layout/drawer/WithSubItems.jsx
- Change Scan Areas "enabled" to "show polygons" to be a bit more accurate
=> Show Polygons

server/src/models/Gym.js
- When querying from DB, raid eggs are now fixed for MAD users
=> Fixes MAD Available Raids Selection

server/src/models/Pokemon.js, server/src/schema/pokemon.js, src/components/tiles/Pokemon.jsx, src/services/queries/pokemon.js
Spread Pokemon that are found nearby (cells and stops) in order to reduce stacking of Pokemon markers
=> Spread Pokemon

src/components/popups/Pokestop.jsx, src/services/Fetch.js
- Adds NPC Rewards (nothing)
- Add support for Invasion lineup forms
=> Add Forms/NPC Reward Support

src/components/popups/Pokestop.jsx
Change back to a classic switch function to get the image url
=> Use switch function in Pokestop Popup

server/src/configs/config.example.json, server/src/services/config.js, src/components/App.jsx, src/services/Fetch.js, src/services/Icons.js
- Update config example to remove pokedave repo
- Add warning if admin sets defaultIcons.misc to anything
- Better caching on the frontend
- Will now load icons from localStorage if the remote repo is unavailable or if the time elapsed is less than the limit set in config
- Invasions received the same treatment
- Also added size multiplier for base set since the gym icons are quite small
=> Better Client Caching

package.json, server/src/schema/pokestop.js, src/assets/scss/main.scss, src/components/tiles/Gym.jsx, src/components/tiles/Pokemon.jsx, src/components/tiles/Pokestop.jsx, src/components/tiles/Timer.jsx, yarn.lock
- Fixes Invasion timers
- Fixes formatting for lures/invasions
- Loops timers in separate component
- Update React Leaflet
=> Fix Timers

.yarnrc, package.json
- Provides better error logging to remind people to update to node 14.x
=> Node Version Reminder

server/src/services/config.js, src/components/App.jsx, src/components/ConfigSettings.jsx, src/services/Icons.js
- Forces misc category to use WWM repo
- Adds `get` method to help with class immutability
=> Uicons - force misc category

src/components/tiles/Gym.jsx
- Small fix to possibly alleviate some cache issues
=> Raid Level Equality Check

server/src/routes/rootRouter.js, server/src/schema/scanArea.js, server/src/schema/schema.js, src/components/Clustering.jsx, src/components/Map.jsx, src/components/QueryData.jsx, src/services/queries/scanAreas.js
- Fixes zoom issue by flooring the zoom
- Fixes logging issue
- Attempt to fix the scanArea issue since it's not repeatable in dev env...
=> GraphQL Fixes

public/base-locales/en.json, server/src/services/createLocales.js, src/components/layout/dialogs/webhooks/Manage.jsx, src/components/layout/dialogs/webhooks/Tracked.jsx, src/components/layout/dialogs/webhooks/WebhookAdv.jsx
- Added "Harmony" override for team 0 to align with poracle tracking references
- Changed order of locale parsing to incl overrides from remote
- Removed hot keys for transitioning tabs as they caused other typing issues
- Fix multi deleting/unselecting
- Fix noIv poracle string
- Fix team poracle string
- Fix raid poracle string
=> Poracle Fixes

server/src/models/Gym.js, src/components/tiles/Gym.jsx
- Adds equality check
- Somehow missed backend filter...
=> Fix in Battle

server/src/schema/poracle.js, src/components/layout/dialogs/webhooks/Manage.jsx, src/components/layout/dialogs/webhooks/WebhookAdv.jsx, src/components/layout/dialogs/webhooks/tiles/TrackedTile.jsx, src/components/layout/general/Notification.jsx, src/components/layout/general/SlideTransition.jsx, src/services/queries/webhook.js
- Removed extra transition component
- Fixed edits so they aren't sending an extra pokemon api request
- Adds GA for webhooks
- Fixes form for nests and removes description
=> Poracle Edit Cleanup

public/base-locales/en.json, server/src/routes/rootRouter.js, server/src/services/discord.js, src/assets/mui/theme.js, src/components/layout/Nav.jsx, src/components/layout/dialogs/Motd.jsx, src/components/layout/dialogs/Search.jsx, src/components/layout/dialogs/UserOptions.jsx, src/components/layout/dialogs/UserProfile.jsx, src/components/layout/dialogs/filters/Advanced.jsx, src/components/layout/dialogs/filters/SlotSelection.jsx, src/components/layout/dialogs/tutorial/Tutorial.jsx, src/components/layout/general/Footer.jsx, src/components/layout/general/Header.jsx, src/components/layout/general/Menu.jsx
- Replace some of the previous code with the more flexible header/footer Components to cut down on unnecessary code
- Also adds try/catch statements for Discord auth for better error hunting
- Fixes profile page for webhooks perm
- General design language consistency improvements
=> Better Utilize Header/Footer Components

server/src/models/Pokemon.js, server/src/schema/pokemon.js, server/src/services/legacyFilter.js, src/components/popups/Pokemon.jsx, src/services/queries/pokemon.js
- Adds inactive stats (where supported) for Ditto display when WB
- Addresses #210
=> Inactive Stats for Ditto

server/src/index.js, server/src/models/Gym.js, server/src/models/Pokemon.js, server/src/models/Pokestop.js, src/components/layout/dialogs/webhooks/WebhookAdv.jsx, src/services/Poracle.js, src/services/queries/pokemon.js, src/services/queries/search.js
- Fixes some missing ts errors
- Adds better networking logs for dev mode, will expand upon later
=> Ts fallback

server/src/services/initWebhooks.js, server/src/services/ui/webhook.js, src/components/layout/Nav.jsx, src/components/layout/dialogs/webhooks/WebhookAdv.jsx, src/hooks/useStyles.js
- Fixes a bug where min cp limits were not respected
- Fixes max cp limit as well
- Dense selections
- Fixes the poracle string a big for league/leagueHigh
- motd fix if set to permanent
- Style adjustment for webhook accordions
=> PVP Adjustments

package.json, public/base-locales/en.json, server/src/configs/default.json, server/src/index.js, server/src/routes/authRouter.js, server/src/routes/clientRouter.js, server/src/routes/rootRouter.js, src/components/App.jsx, src/components/Auth.jsx, src/components/Errors.jsx, src/components/Login.jsx, src/services/Fetch.js
- Adds some redirects and basic error pages to at least show something when a server side error occurs
- Custom auth endpoints via config
- Version on client side for debugging
=> Error Redirects

server/src/configs/default.json, server/src/models/Portal.js
- Doesn't return portals X days old
- Defaults to 30 days
=> Add Portal Updated Since Limit

server/src/services/DiscordClient.js, server/src/services/events/guildMemberRemove.js, server/src/services/events/guildMemberUpdate.js, server/src/strategies/discord.js, server/src/strategies/telegram.js
- Move client.on to the strategy so it can be set for each discord bot/strategy
- Rename discord.js => DiscordClient.js
=> Separate Discord Clients

public/base-locales/en.json, server/src/routes/rootRouter.js, server/src/services/Utility.js, server/src/services/ui/advMenus.js, src/components/ConfigSettings.jsx, src/components/layout/dialogs/filters/OptionsContainer.jsx, src/components/layout/general/Menu.jsx
- Adds some hint text in case no results are returned in the filter menus
=> No Results Found Text

src/components/markers/device.js, src/components/markers/gym.jsx, src/components/markers/nest.jsx, src/components/markers/pokemon.jsx, src/components/markers/pokestop.jsx, src/components/markers/typeCell.js, src/components/markers/weather.jsx, src/services/Icons.js
- For the admins that have customized the icon layout a bit and want some finer adjustments for the popup anchor
- Uses addition, defaults to 0,0
=> Adds Popup Anchor Adjustments

src/components/popups/Gym.jsx, src/components/tiles/Gym.jsx
- Show boss countdown if it has been revealed but still unhatched
- Show moveset before hatch time
=> Raid Adjustments

src/components/layout/dialogs/webhooks/tiles/TrackedTile.jsx, src/services/Poracle.js
- Forces invasion grunt_type to be lowercase due to PoracleWeb inserting entries incorrectly
=> Force Invasion Lowercase

public/base-locales/de.json, public/base-locales/en.json, server/src/routes/rootRouter.js, src/components/Login.jsx, src/components/layout/dialogs/tutorial/Welcome.jsx, src/components/layout/general/DiscordLogin.jsx, src/components/layout/general/LocaleSelection.jsx
- Add locale keys for sizing the buttons, for the germans
- Also makes some adjustments for adding the locale selection to the login page in the localAuth PR
=> Login Page Adjustments

server/src/configs/default.json, server/src/models/Gym.js, server/src/routes/rootRouter.js, server/src/schema/gym.js, src/components/markers/gym.jsx, src/components/popups/Gym.jsx, src/components/tiles/Gym.jsx, src/services/queries/gym.js
- Correct long time spelling error
- Backwards compatible still
- Also add raidBoss.size check
=> Spelling Correction

server/src/configs/default.json, server/src/db/initialization.js
- Configurable max connections to db, default is 10
=> Add Max Connections

src/assets/scss/main.scss, src/components/Map.jsx, src/components/QueryData.jsx, src/components/layout/dialogs/Search.jsx, src/components/markers/pokestop.jsx, src/components/tiles/Gym.jsx, src/components/tiles/Nest.jsx, src/components/tiles/Pokemon.jsx, src/components/tiles/Weather.jsx
- Adds fallback amounts if the UICONS repo is missing the amount image
- On map marker display
- Search display
- Now builds a sizeKey upon filter adjustment, which sets if an item should rerender, forcing rerenders if sizes change
- Remove iffy size memo functions
- Weather memoization
=> Fallback Amounts/Size Fixes/Memoize Weather

public/base-locales/en.json, server/src/graphql/resolvers.js, server/src/routes/clientRouter.js, src/components/App.jsx, src/components/ClearStorage.jsx, src/components/ConfigSettings.jsx, src/components/Errors.jsx, src/components/layout/drawer/Settings.jsx, src/components/tiles/Weather.jsx
- More weather memo checks
- Keep weather popup open upon refresh
- Tutorial logic for non-logged in users
- Back button on error pages (since Safari doesn't show the full address and users think they're refreshing the right page)
- Adds reset path to help users clear storage if they're experiencing issues
=> Christmas Eve Features and Fixes

src/components/popups/Pokestop.jsx, src/services/functions/parseConditions.js
- Checks if there is a valid quest_title
- Defaults to RM translations if not
- Also overrides POI quest_title
=> Quest Title Check

src/services/Icons.js
Apparently promise.all can't be trusted :cry:
=> Remove Promise.all uicons

server/src/configs/default.json, src/components/layout/Nav.jsx, src/components/layout/dialogs/Motd.jsx
- Allows showing the entire motd for donor or non-donor only
=> Motd Perm Tweaks

public/base-locales/en.json, server/src/models/Pokemon.js, server/src/services/legacyFilter.js, src/components/popups/Pokemon.jsx
- Adds cell pokemon indicator in popup
- Adds tooltip for verified/unverified timers
- Also fixes seen_type for legacy filtering
=> Cell Pokemon & Tooltips

src/components/markers/nest.jsx
- Offset X and Y for Pokemon
- Popups as well
=> Nest Icon Mods

src/components/Map.jsx, src/services/filtering/genPokestops.js
- Mega Energy
- Candy
- XL Candy
- Also a check for clustering settings
=> Add some extra checks to filter generating

public/base-locales/de.json, public/base-locales/en.json, server/scripts/configMigration.js, server/src/graphql/typeDefs.js, server/src/models/Pokestop.js, server/src/services/config.js, server/src/strategies/discord.js, server/src/strategies/local.js, server/src/strategies/telegram.js, src/components/App.jsx, src/components/layout/auth/Login.jsx, src/components/layout/dialogs/UserProfile.jsx, src/components/layout/dialogs/webhooks/WebhookAdv.jsx, src/components/layout/dialogs/webhooks/tiles/TrackedTile.jsx, src/services/Poracle.js, src/services/apollo.js, src/services/queries/search.js
- Move Apollo to own function
- Remove ts from questSearch since it's unnecessary and was breaking things...for no apparent reason
- Remove skipUndefined()
- Fix both gender invasions displaying in the webhook menu
=> Global Search & Poracle Invasions

src/components/layout/auth/Local.jsx
- Disables login/register button while user waits for api call to finish
=> Adds on submit check

server/src/index.js, server/src/routes/rootRouter.js, server/src/services/Fetch.js, server/src/services/checkForUpdates.js, server/src/services/logUserAuth.js, server/src/strategies/telegram.js
- check for latest updates functionality based off of current git branch
- shorten fetch class method names
=> Check for Latest Updates

public/base-locales/en.json, public/base-locales/pl.json, src/components/layout/Nav.jsx, src/components/layout/dialogs/ResetFilters.jsx, src/components/layout/drawer/Settings.jsx, src/hooks/useStore.js
Tested locally - everything works as intended. I hope the code is clean enough ;)
=> Add 'Reset filters' dialog

server/src/routes/rootRouter.js
- Fixes the session tutorial when forceTutorial = false in config
=> Fix Tutorial for forceTutorial = false

src/assets/scss/main.scss, src/components/markers/device.js, src/components/markers/nest.jsx, src/components/markers/pokemon.jsx, src/components/markers/weather.jsx, src/services/Icons.js
- Additional Nest adjustments
- New nest modifier field `nestMonMulti`
- Additional Weather adjustments
- New weather modifier field `disableColorShift`
- Additional Device adjustments
- Fix icon centered for small size Pokemon
- getPopupOffset => getModifiers method in Icons
Addresses #343 and various Discord bug reports.
=> Icons Adjustments

public/base-locales/nl.json, public/index.template.html, src/components/App.jsx
=> Update Dutch translations

public/base-locales/de.json
=> translation correction for slider_little (PVP League WP 500)

server/src/configs/default.json, server/src/models/Filters.js, server/src/routes/rootRouter.js, server/src/services/defaultFilters/buildDefaultFilters.js
- Config option to enable all pokes by default (not recommended)
Was in the mood for a short PR :lappy:
=> Enable All Pokes

package.json, src/index.jsx
- Return nothing if an external library has an error
- Version Bump
=> Block Error Reports for Node Modules

server/src/graphql/resolvers.js, server/src/models/Pokestop.js, server/src/strategies/telegram.js, src/components/layout/dialogs/Search.jsx, src/index.jsx
- Regex to only allow a-z/0-9
- traceSampleRates parsing
=> Block Rude Searches

public/base-locales/nl.json
Before edit it was "Toevoegen gym toe aan poracle" this is not correct dutch now it will show "Voeg gym toe aan poracle"
=> Update NL translation

src/components/layout/general/QuestTitle.jsx, src/components/popups/Pokestop.jsx
- Follows new pogo-translations format for better respecting the protos
=> Quest Title Adjustments

server/src/models/Gym.js, src/components/layout/dialogs/filters/SlotSelection.jsx, src/components/popups/Gym.jsx, src/components/tiles/Gym.jsx
- Rework backend gym filtering to be a bit cleaner and more efficient
- Fix all gyms being marked as AR
- Fixes #392
=> Gym Backend Filtering v2

src/components/tiles/Pokemon.jsx
Fix Pokemon randomly drifting. Untested.
=> Use pseudorandom offsets

public/base-locales/en.json, src/components/markers/device.js, src/components/markers/spawnpoints.js, src/components/popups/Device.jsx, src/components/popups/Pokemon.jsx, src/components/tiles/Device.jsx, src/components/tiles/Spawnpoint.jsx, src/services/Icons.js
- Device & Spawnpoint Folders
- Option to use spawnpoint images instead of leaflet shapes
=> Latest Uicons

src/components/ConfigSettings.jsx, src/components/layout/dialogs/UserProfile.jsx
- Add username to profile page
- Addresses #395
=> Username on Profile Page

server/src/configs/default.json, src/components/layout/dialogs/UserProfile.jsx
- Set custom directory
- Include images for perms that are arrays if desired
- Addresses #387
=> Custom perm images

server/src/configs/default.json, server/src/models/Gym.js, server/src/models/Pokestop.js
- Hide old stops and gyms
- "Fixes" #413
=> Hide Old Forts

src/components/Map.jsx, src/components/QueryData.jsx, src/components/layout/Nav.jsx, src/components/layout/general/ActiveWeather.jsx, src/hooks/useStore.js
- Move weather into query component, so it turns off when weather is disabled
- Move isMobile/isTablet into map component, so it can be passed to active weather
- Make icon smaller when mobile
- Fix color shift for certain uicons sets
=> Adjust Active Weather

public/base-locales/en.json, src/hooks/useLocation.js
Add translatable text for Leaflet Locate Control
=> Translate Locate Control

package.json, server/src/graphql/resolvers.js, server/src/models/Gym.js, server/src/models/Pokemon.js, server/src/services/DbCheck.js, server/src/services/PvpWrapper.js, server/src/services/legacyFilter.js, yarn.lock
- Cache PVP results by encounter id and updated with TTL for cleaning
- Remove ohbem from Db class and make it into its own extended class
- Cleanup methods
- Add node cache
=> Dramatically Optimize Internal PVP

server/src/graphql/resolvers.js
=> Filter out hidden

package.json, server/knexfile.cjs, server/scripts/generateMasterfile.js, server/src/graphql/resolvers.js, server/src/index.js, server/src/routes/api/apiIndex.js, server/src/routes/rootRouter.js, server/src/services/DbCheck.js, server/src/services/EventManager.js, server/src/services/api/fetchJson.js, server/src/services/config.js, server/src/services/events/guildMemberRemove.js, server/src/services/geocoder.js, server/src/services/initialization.js, server/src/services/logUserAuth.js, server/src/strategies/local.js, server/src/strategies/telegram.js, src/components/popups/Pokemon.jsx, yarn.lock
- Update ohbem to latest
- Add ohbem masterfile updating to event manager
- Various console logs updates
- Fix pvp uicons costumes
=> Add warnings/update ohbem

server/src/services/functions/getPlacementCells.js, src/components/Clustering.jsx, src/components/tiles/submissionCells/SubmissionCell.jsx
- Occasionally led to duplicate submission cell rings
- Simplified ID function
=> Fix Dupe Submission Cell Issues

.eslintrc, public/base-locales/en.json, server/src/graphql/scannerTypes.js, server/src/models/Gym.js, server/src/models/Pokestop.js, src/components/layout/dialogs/Search.jsx, src/components/markers/gym.jsx, src/components/markers/pokestop.jsx, src/components/popups/Device.jsx, src/components/popups/Gym.jsx, src/components/popups/Nest.jsx, src/components/popups/Pokemon.jsx, src/components/popups/Pokestop.jsx, src/components/popups/S2cell.jsx, src/components/popups/Weather.jsx, src/components/popups/common/PowerUp.jsx, src/components/popups/common/TimeTile.jsx, src/components/popups/common/Timer.jsx, src/components/tiles/Gym.jsx, src/components/tiles/Pokestop.jsx, src/components/tiles/Timer.jsx, src/services/Utility.js, src/services/functions/formatInterval.js, src/services/queries/gym.js, src/services/queries/pokestop.js
- Fort power ups
- Points/Day/Days translation keys
- Adjust some eslint rules
- Fix some translation issues
=> Add Fort Power Ups

server/src/models/Pokestop.js, server/src/routes/api/v1/sessions.js, server/src/services/EventManager.js
- Fix ambiguous `update` field
- Fix logic for getting available invasions from a multiInvasion db
- Add a timeout to do initial available queries safely after the db settings are initialized
=> Fix Multi Invasions

public/base-locales/es.json, public/base-locales/fr.json, public/base-locales/it.json, public/base-locales/ja.json, public/base-locales/ko.json, public/base-locales/nl.json, public/base-locales/pt-br.json, public/base-locales/ru.json, public/base-locales/sv.json, public/base-locales/th.json, public/base-locales/tr.json, public/base-locales/zh-tw.json
@pjorritsma want to double check NL?
@Petap0w same for FR?
@lenisko / @kamieniarz  I left PL off the machine translations as previously requested, if either of you want to add it to this PR
=> Missing Translations

server/src/strategies/telegram.js
This allows setting user specific permissions
=> Added user id to array of chat id's to check in TG auth

server/src/configs/areas.example.json
Improved the format in the example file to better display the order of longitude and latitude, and that the first and last coordinates of the fence need to be the same.
=> Improved areas.example.json

server/scripts/poracleToGeoJSON.js
If the first and last coordinates of a polygon aren't identical, add the first coordinates to the end.
=> Edited poracleToGeoJSON.js to check for coordinate format

package.json, public/base-locales/en.json, server/scripts/createLocales.js, server/src/graphql/mapTypes.js, server/src/graphql/resolvers.js, server/src/models/Filters.js, server/src/models/Gym.js, server/src/models/Nest.js, server/src/models/Pokemon.js, server/src/models/Pokestop.js, server/src/routes/rootRouter.js, server/src/services/DbCheck.js, src/components/layout/dialogs/filters/Advanced.jsx, src/components/layout/dialogs/filters/MenuTile.jsx, src/services/queries/available.js
- Filter quests by their conditions now if a reward has multiple conditions
- Rework available, returns an object instead now for future expandability
- questConditions gql api update
- version bump
- Make better use of promise.all in getAvailable pokestops method to reduce query time
s
=> Filter by Quest Conditions

public/base-locales/en.json, server/src/configs/custom-environment-variables.json, server/src/configs/default.json, server/src/services/ui/clientOptions.js, src/components/layout/dialogs/UserOptions.jsx, src/components/tiles/ScanArea.jsx
Client side option to always have labels displayed or not
=> Optional show labels

.github/workflows/release.yml, package.json
- Minor version bump
- Sentry cli for releases
=> Automated Releases

server/src/graphql/resolvers.js, server/src/services/functions/getPlacementCells.js, src/components/Container.jsx, src/components/tiles/submissionCells/Ring.jsx
- Bring circles into their own pane with a higher zIndex
- Better filtering on backend
=> Wayfarer Tweaks & Fixes

package.json, public/base-locales/en.json, server/src/configs/custom-environment-variables.json, server/src/configs/default.json, server/src/models/Gym.js, server/src/models/Pokestop.js, server/src/services/defaultFilters/buildDefaultFilters.js, server/src/services/ui/primary.js, src/components/layout/drawer/WithSubItems.jsx
- Adds a multi button for filtering powered up gyms and stops
- Includes backend support for both gyms and stops
=> Poi Power Up Filtering

public/base-locales/en.json, src/components/popups/Pokemon.jsx, src/components/tiles/Pokemon.jsx
- Scatter lure pokemon
- Captioning for non-encounter spawns to explain to the user
=> Extra Lure Support

package.json, server/src/configs/default.json, server/src/services/EventManager.js, src/components/popups/Pokestop.jsx
- Use new invasions endpoint
- Version bump
=> Update Invasions Endpoint

src/components/layout/FloatingBtn.jsx
LocationOn -> MyLocation as this icon is more common.
=> use more common icon for use-my-location

package.json, src/components/tiles/Gym.jsx, src/components/tiles/Pokemon.jsx, src/components/tiles/Pokestop.jsx
- Update to make them accurate with current game mechanics
- Make the color different for lure range
=> adjust interaction ranges

package.json, src/components/layout/custom/Generator.jsx
- Add locale selection to loginPage/donationPage/motd
- Set type = "localeSelection" in the config
- Resolves #591
=> add locale selector

package.json, server/src/models/Filters.js, server/src/models/Pokemon.js, server/src/services/api/fetchRaids.js, server/src/services/defaultFilters/buildDefaultFilters.js, src/components/layout/dialogs/filters/Advanced.jsx, src/components/layout/dialogs/filters/Gender.jsx, src/components/layout/drawer/MultiSelector.jsx, src/components/layout/drawer/Pokemon.jsx
=> Pokemon Gender Filtering

server/src/models/Pokestop.js, server/src/services/DbCheck.js
Guessed support for multi invasion mad table
=> Multi invasions mad

package.json, server/src/models/Pokestop.js, src/components/Config.jsx, src/components/tiles/Pokestop.jsx, src/services/Icons.js
- Docker env var fixes from fabio
- Pokestop filtering fixes
=> Sync Dev to Main

server/src/models/Nest.js, server/src/services/DbCheck.js, src/components/popups/Nest.jsx, src/components/tiles/Nest.jsx
- Support binary type `polygon` column
- Converts existing into a feature instead
- Displays feature instead of polygon component for nests
=> Binary nest polygon

src/components/layout/dialogs/webhooks/Areas.jsx
=> respect poracle area groups

public/base-locales/en.json, server/src/services/ui/webhook.js, src/components/layout/dialogs/webhooks/WebhookAdv.jsx, src/components/layout/dialogs/webhooks/tiles/TrackedTile.jsx, src/components/layout/general/Menu.jsx, src/hooks/useFilter.js, src/services/Icons.js, src/services/Poracle.js, src/services/filtering/genPokestops.js
=> poracle event stop support

package.json, src/components/layout/FloatingBtn.jsx, src/components/layout/Nav.jsx, src/components/layout/drawer/Areas.jsx, src/components/layout/drawer/Buttons.jsx, src/components/layout/drawer/Drawer.jsx, src/components/layout/drawer/Section.jsx, src/components/layout/drawer/Settings.jsx, src/components/layout/drawer/WithSubItems.jsx
- refactor the code and state for the drawer a bit to reduce ugliness
- move buttons outside of the settings panel
=> drawer refactor

src/components/ReactRouter.jsx, src/hooks/useConfig.js, src/hooks/useRefresh.js
- reduce renders on startup
- fix long standing bug when changing translations
=> more state optimizations

src/assets/css/main.css, src/components/layout/custom/AdvancedAccordion.jsx, src/components/layout/dialogs/scanner/ScanNextTarget.jsx, src/components/layout/dialogs/scanner/ScanZoneTarget.jsx, src/components/layout/dialogs/scanner/Shared.jsx
- Move from grid to lists
- Share some code between them
- Remove the pointless slider
=> rework both scan on demand popups

package.json, server/src/graphql/typeDefs.js, server/src/models/Weather.js, src/components/QueryData.jsx, src/services/queries/weather.js, yarn.lock
- Send bounds to weather endpoint to filter by bounds
- Also fixes some inconsistencies with weather and area Restrictions
- Now does a pointInPolygon, booleanOverlap, and booleanContains to check for all 3 possibilities
Resolves #681
=> weather bounds

src/components/popups/Pokestop.jsx, src/components/popups/common/TimeTile.jsx
- Change behavior of invasion expansion
- Add caption for lure type
Resolves #684
=> pokestop popup adjustments

package.json, server/src/routes/api/v1/users.js, server/src/services/DbCheck.js
- adds `GET` `/api/v1/users/export`
- returns an array of all users with their backups and badges appended to each user object
- excludes id column since it doesn't matter
- adds `POST` `/api/v1/users/import`
- where the body of the request is in the same format as the export route returns
- version bump
=> import & export reactmap users via api

package.json, server/src/graphql/mapTypes.js, server/src/graphql/scannerTypes.js, server/src/models/Gym.js, server/src/services/DbCheck.js, src/components/layout/dialogs/Search.jsx, src/components/markers/gym.jsx, src/components/markers/pokestop.jsx, src/components/popups/Gym.jsx, src/components/popups/Pokestop.jsx, src/services/Icons.js, src/services/functions/getRewardInfo.js, src/services/queries/gym.js, src/services/queries/search.js
- Adds support for `raid_pokemon_alignment` field in the gym column
- And latest uicons `_a{alignment}` flag
=> raid alignment field support

package.json, server/src/configs/local.example.json, server/src/services/EventManager.js, server/src/services/config.js, src/components/layout/dialogs/Search.jsx, src/components/layout/dialogs/tutorial/Popups.jsx, src/components/markers/pokestop.jsx, src/components/popups/Pokestop.jsx, src/services/Icons.js, src/services/functions/getRewardInfo.js
- add support for webp (and all other) format of uicons
- set new default to be the new webp uicons repo
- version bump
=> Support all image formats for uicons

src/components/Config.jsx, src/hooks/useConfig.js
set page title after settings are fetched
=> fix setting page title

public/base-locales/en.json, src/components/Map.jsx, src/components/QueryData.jsx, src/components/tiles/S2Cell.jsx
- move s2 cell generation to the client since the data is generic anyway, still "follows" permissions
- saves server processing
=> move s2 cell generation to the client

public/base-locales/en.json, server/src/configs/custom-environment-variables.json, server/src/configs/default.json, server/src/services/ui/clientOptions.js, src/components/popups/Gym.jsx, src/components/popups/Pokemon.jsx, src/components/popups/Pokestop.jsx, src/components/popups/Portal.jsx, src/components/tiles/Gym.jsx
Don't default everything to a spoofer map. Move Coords to client side settings.
=> Move Coords to Client Side Settings

index.html, src/components/layout/FloatingBtn.jsx, src/components/layout/auth/Discord.jsx, src/components/layout/custom/CustomButton.jsx, src/components/layout/drawer/Actions.jsx, src/components/layout/general/FAIcon.jsx
- update font awesome to latest
- replace mui icon component with my own
=> update font awesome

server/src/models/Pokestop.js
- Filter invasion mons by whether they're actually catchable, compared to all mons in the grunt battle
=> better invasion filtering for specific mons

src/components/popups/Gym.jsx
- Shows the costume name
- Drops showing mega, since the reward pokemon is never a mega anyway
Resolves #741
=> fix: show raid reward costume name

server/src/models/Gym.js, src/components/layout/drawer/Extras.jsx, src/components/layout/drawer/MultiSelector.jsx
Resolves #541 
Click the currently selected to set `none` and show gyms without badges
=> feat: filter gyms without a badge

src/assets/css/main.css, src/components/markers/gym.jsx, src/components/popups/Gym.jsx
- Show gym badge info in popup
- If badge is present, show an appropriate gradient around the image
- Show team badge in popup too
Resolves #554
=> feat: show badge info in popup

src/components/layout/dialogs/webhooks/Error.jsx, src/components/layout/dialogs/webhooks/Manage.jsx, src/services/Poracle.js
- Display the actual error in the webhook dialog
- Optional chaining to fix errors when missing some reactmap perms
Resolves #353
=> poracle perm fixes

public/base-locales/en.json, src/components/layout/drawer/Actions.jsx
- adds a contribute button in the drawer
=> add contribute button

src/components/QueryData.jsx, src/services/apollo/AbortableContext.js, src/services/apollo/AbortableLink.js, src/services/apollo/RobustTimeout.js
=> Clean up robust timeout on cleanup

src/components/layout/dialogs/tutorial/Closing.jsx, src/components/layout/dialogs/tutorial/Sidebar.jsx, src/components/layout/dialogs/tutorial/Tutorial.jsx, src/components/layout/drawer/ItemToggle.jsx, src/hooks/useConfig.js
- More consistent tutorial persisting for non-logged in users
- Styling adjustments
=> fix: better tutorial persisting

package.json, public/base-locales/en.json, server/src/index.js, server/src/models/Nest.js, src/components/QueryData.jsx, src/components/layout/dialogs/NestSubmission.jsx, src/components/popups/Nest.jsx, src/hooks/useStore.js
- Provides extra feedback during the nest submission process 
- Small rework of error logging for gql
- Small bug related to leaflet and mui dialogs not working well together
=> fix: better nest submission feedback

package.json, public/base-locales/en.json, server/src/configs/local.example.json, server/src/db/migrations/20210407180251_discordUsers.cjs, server/src/db/migrations/20210928021816_passport-options.cjs, server/src/db/migrations/20211119195323_local-auth.cjs, server/src/db/migrations/20211228173232_link_discord_telegram.cjs, server/src/db/migrations/20220116023217_gym_tracking.cjs, server/src/db/migrations/20221006032139_add_data_column.cjs, server/src/db/migrations/20230316021148_backups.cjs, server/src/db/migrations/20230722200327_nest-submissions.cjs, server/src/db/migrations/migration.stub.cjs, server/src/graphql/resolvers.js, server/src/graphql/scannerTypes.js, server/src/graphql/typeDefs.js, server/src/models/Backup.js, server/src/models/Badge.js, server/src/models/Gym.js, server/src/models/Nest.js, server/src/models/NestSubmission.js, server/src/models/Session.js, server/src/models/User.js, server/src/models/index.js, server/src/services/DbCheck.js, server/src/services/config.js, server/src/types.d.ts, src/components/markers/pokestop.jsx, src/components/popups/Nest.jsx, src/services/queries/nest.js
- Adds a nest submission table for manually overriding the nest name
- `nest_id`, `name`, `submitted_by`, `user_id`
- Ran prettier on existing migrations
- I got sidetracked and wrote A LOT of jsdocs for existing models `DbCheck` class to help with future dev
=> Nest submission table

ReactMap.js, locales/scripts/create.js, server/scripts/generateMasterfile.js, server/src/configs/default.json, server/src/index.js, server/src/services/Clients.js, server/src/services/DbCheck.js, server/src/services/config.js, server/src/services/filters/pokemon/constants.js, server/src/services/logger.js
- Fixes some issues with calling the `server/src/services/config.js` file multiple times from external services. 
- Starts to make better use of how the config library is supposed to be used
- Allows setting log level in the config once again
- Needs a larger refactor in the long term
=> fix: config calls

server/src/models/Pokestop.js, src/components/layout/dialogs/filters/Advanced.jsx
- Allows selecting multiple quest conditions to filter by in the adv quest menu
Resolves #782
=> feat: multiple quest conditions

locales/en.json, server/src/configs/default.json, server/src/models/Spawnpoint.js, server/src/services/filters/builder/base.js, src/components/layout/drawer/Extras.jsx
- Adds spawnpoint tth filtering 
- Options: `0, 1, 2`
- 0 = "all"
- 1 = "known"
- 2 = "unknown"
Resolves #753
=> feat: spawnpoint tth filtering

.gitignore, server/src/index.js, server/src/routes/api/v1/area.js, server/src/services/areas.js
- `/api/v1/area/reload`
- Reloads areas in memory
- Needs https://github.com/TurtIeSocks/Koji/pull/191
Resolves #799
=> feat: reload areas api

.gitignore, server/src/services/api/fetchJson.js, server/src/services/filters/pokemon/Backend.js
- Logs fetch errors to a file
- New `logs` folder in root, will be used for various things in the future
- Cleans filters to ensure more consistent requests are sent to golbat
=> fix: Log fetch errors & cleaner golbat api requests

package.json, src/components/Map.jsx, src/hooks/useConfig.js
- Reverts `useLayoutEffect` change => `useEffect` when adding leaflet location controls
- Better checking for valid url params
=> fix: url params + revert location select to `useEffect`

package.json, src/components/layout/dialogs/tutorial/Sidebar.jsx
- Fixes a component in the tutorial when the user does not have the correct permissions
- Bump to 1.23.3
=> fix: tutorial sidebar component

package.json, packages/locales/lib/human/en.json, packages/logger/lib/index.js, packages/types/lib/augmentations.d.ts, packages/types/lib/client.d.ts, server/src/graphql/resolvers.js, server/src/models/Backup.js, server/src/services/DiscordClient.js, server/src/services/TelegramClient.js, server/src/services/api/Poracle.js, server/src/services/checkForUpdates.js, src/assets/mui/theme.js, src/components/layout/FloatingBtn.jsx, src/components/layout/auth/Blocked.jsx, src/components/layout/auth/Discord.jsx, src/components/layout/auth/Login.jsx, src/components/layout/auth/Telegram.jsx, src/components/layout/custom/CustomButton.jsx, src/components/layout/custom/Generator.jsx, src/components/layout/custom/LinkWrapper.jsx, src/components/layout/dialogs/filters/Options.jsx, src/components/layout/dialogs/filters/OptionsContainer.jsx, src/components/layout/dialogs/webhooks/Manage.jsx, src/components/layout/dialogs/webhooks/Selecting.jsx, src/components/layout/dialogs/webhooks/Tracked.jsx, src/components/layout/dialogs/webhooks/store.js, src/components/layout/dialogs/webhooks/tiles/TrackedTile.jsx, src/components/layout/general/Menu.jsx, src/components/popups/Gym.jsx, yarn.lock
- Returns the tooltip to the webhook fab
- Fixes log colors for pm2
- Sort tracked poracle records on the backend
- Update checking for docker
- Redirect from login page if already logged in 
- Check for TG ref before removal from dom
- Gym selector badge in gym popup fix
- Better experience when viewing poracle tracks
- Should reduce the chances of a double scrollbar
- Better behavior for the `cancel` / `select all` / `delete all` buttons
=> Fixes following the merge of #810

server/src/services/areas.js
fix for selecting the correct area file for multi-domains
=> multi-domain area fix

server/src/services/areas.js, src/components/Container.jsx, src/components/Layers.jsx, src/components/Map.jsx, src/hooks/useTileLayer.js
- Puts TileLayer, Locate, and Zoom controls in their own components
- Better performance and lifts them away from the dreaded `Map` component
- Also ensures better loading order consistency
=> feat: put leaflet layers in their own components

README.md
=> Minor Text Fix for Node Version

packages/locales/lib/human/en.json, src/assets/mui/theme.js, src/components/ErrorBoundary.jsx, src/components/layout/custom/Generator.jsx, src/features/playground/components/MainMenu.jsx, src/features/playground/components/Viewer.jsx, src/features/playground/hooks/useSafeParse.js
- Load from last auto save feature. If something crashes, your last successfully parsed json will be saved and can be loaded from local storage
- Error boundary around the viewer, with a reset view button
- Optional value checker on the button color logic
=> feat: playground qol improvements

package.json, server/src/graphql/typeDefs/poracle.graphql, server/src/services/api/Poracle.js, src/components/layout/dialogs/webhooks/human/profile/EditView.jsx, src/components/layout/dialogs/webhooks/human/profile/ProfileView.jsx
- Fixes poracle profile management
- Better UID generation for `active_hours`
- Ensure a proper `active_hours` json is being sent to the Poracle API 
- Change icon to `MoreTime` which is 1000x more appropriate 
- Better state updating
- Invalid `active_hours` created with the bad code before this may need to be deleted before things work correctly
=> fix: poracle profile management

package.json, packages/locales/lib/human/en.json, server/src/graphql/server.js, server/src/services/api/Poracle.js, src/components/layout/FloatingBtn.jsx, src/components/layout/dialogs/filters/AdvSearch.jsx, src/components/layout/dialogs/scanner/Marker.jsx, src/components/layout/dialogs/webhooks/Manage.jsx, src/components/layout/dialogs/webhooks/Tracked.jsx, src/components/layout/dialogs/webhooks/hooks.js, src/components/layout/dialogs/webhooks/human/Draggable.jsx, src/components/layout/dialogs/webhooks/human/Location.jsx, src/components/layout/dialogs/webhooks/human/profile/NewProfile.jsx, src/components/layout/dialogs/webhooks/human/profile/index.jsx, src/components/layout/dialogs/webhooks/human/status/EnableSwitch.jsx, src/components/layout/dialogs/webhooks/human/status/HookSelection.jsx, src/components/layout/dialogs/webhooks/human/status/ProfileSelect.jsx, src/components/layout/dialogs/webhooks/human/status/index.jsx, src/components/layout/dialogs/webhooks/tiles/TrackedTile.jsx, src/services/Poracle.js
- Fixes poracle location updating when it's not supposed to
- Memoizes the webhook search component
- Always render the human tab (but set hidden when not in use) but only render the other categories when selected
- Remove `close` button on profile page, I think this was just confusing more than anything else
- Styling
- Generate poracle description when searching if it's missing
- Change the icon to try and indicate "Done" rather than "Save" when setting location or areas for webhooks
- `done`
- `bitcoin` and `pound` can now be used as a logo for the `donorPage` fab
=> fix: Poracle location & others

server/src/configs/default.json, server/src/services/DiscordClient.js, server/src/services/logUserAuth.js
=> feat: switch for hiding pii on channel log

server/src/services/DiscordClient.js
fix to match default.json sorry!
=> fix: rename log pii config value

server/src/configs/default.json, server/src/models/Route.js, server/src/services/functions/getClientTime.js
- Filter routes by an admin configurable number of days
Resolves #846
=> feat: filter routes by updated

.gitignore
https://developer.android.com/training/app-links/verify-android-applinks
=> Add Android App Link support

server/src/models/Pokemon.js, server/src/services/filters/pokemon/Backend.js
- Better handling of global filters and `link globa & advanced` to stop returning unnecessary results from Golbat
=> fix: v2 golbat api fixes

packages/locales/lib/human/en.json, src/components/Config.jsx, src/components/HolidayEffects.jsx, src/components/layout/drawer/BoolToggle.jsx, src/components/layout/drawer/Settings.jsx, src/hooks/useStore.js, src/services/functions/checkHoliday.js, src/services/functions/setDeep.js
=> Disable Holidays Client Side

src/components/Config.jsx, src/components/Errors.jsx, src/components/ReactRouter.jsx, src/components/layout/auth/Blocked.jsx, src/hooks/useHideElement.js
Resolves #866 
- Makes sure to fetch server settings before rendering blocked page
- Also makes sure to hide the ghetto html loading el
=> fix: blocked page

package.json, packages/types/lib/scanner.d.ts, packages/types/lib/server.d.ts, server/src/configs/default.json, server/src/graphql/typeDefs/scanner.graphql, server/src/models/Pokestop.js, server/src/services/DbCheck.js, server/src/services/EventManager.js, server/src/services/filters/builder/pokestop.js, server/src/services/ui/advMenus.js, src/components/layout/dialogs/filters/MenuTile.jsx, src/components/popups/Pokestop.jsx, src/services/filtering/genPokestops.js, src/services/queries/pokestop.js
Adds backwards compatible support for https://github.com/UnownHash/Golbat/pull/188
=> feat: showcase form support

server/src/models/Pokemon.js, server/src/services/filters/pokemon/Backend.js
Rewrite of #861 that works correctly.
=> Fix pkmn filters

packages/locales/lib/human/en.json, packages/locales/lib/human/pl.json, server/src/services/DiscordClient.js, src/components/layout/auth/Blocked.jsx, src/components/layout/auth/Discord.jsx
=> feat: show signed in info when blocked

packages/locales/lib/human/en.json, packages/locales/lib/human/pl.json, src/components/layout/auth/Blocked.jsx
Refers to https://github.com/WatWowMap/ReactMap/pull/896
Header is now easier to translate
=> Make translation easier for blocked page

src/hooks/useTileLayer.js
=> Tile layer bg

.github/workflows/lint.yml, .github/workflows/main.yml, .github/workflows/release.yml, .husky/commit-msg, .husky/pre-commit, package.json, yarn.lock
Adds some CI and commit hooks to automate RM's releases a bit
=> feat: ci for github releases

server/src/services/ui/primary.js
Fixes a bug that shows some sub categories (without functionality) to users without the respective perms.
=> fix: subcategory viewing

package.json, src/components/QueryData.jsx, src/services/apollo/RobustTimeout.js, yarn.lock
- Upgrades apollo client and server versions
- Fixes some stale state related to robust timeout class
=> chore: upgrade apollo

server/src/routes/rootRouter.js, src/components/ErrorBoundary.jsx, src/components/QueryData.jsx, src/components/layout/dialogs/filters/Advanced.jsx, src/components/layout/dialogs/filters/FilterMenu.jsx, src/components/layout/dialogs/filters/SlotSelection.jsx, src/components/layout/dialogs/webhooks/Tracked.jsx, src/hooks/useLayoutStore.js
Maybe more consistent decoding of minified errors by changing up the regex
=> fix: better regex for mapping minified errors

package.json, src/assets/css/main.css, src/components/layout/dialogs/filters/Advanced.jsx, src/components/layout/dialogs/profile/GymBadges.jsx, src/components/layout/dialogs/profile/index.jsx, src/components/layout/general/Menu.jsx, src/services/filtering/applyToAll.js, yarn.lock
Fixes some styling on the gym badge profile page
=> fix: gym badge page styling

src/components/layout/dialogs/BadgeSelection.jsx, src/components/layout/dialogs/profile/GymBadges.jsx, src/components/popups/Gym.jsx
- Fixes badge count (bronze and gold were reversed)
- Fixes badge updating when changing it from popup
- Fixes badge display when badge = null
Resolves #924
=> fix: gym badge fixes

packages/locales/lib/human/en.json, src/components/QueryData.jsx, src/components/layout/Nav.jsx, src/components/layout/dialogs/ClientError.jsx, src/hooks/useRefresh.js, src/services/functions/deepMerge.js
This fixes an issue where sometimes a cached version of the map is saved in a user's browser, most commonly when a user is using the built in Discord browser, and the outdated cache does not align with the server version. This previously caused nothing at all to load on the map and no feedback to the user. This now catches the error earlier on and displays a lengthy error on how the user might fix it.
=> fix: early version check

src/components/layout/drawer/Actions.jsx
Fixes two problems:
- When a user imported a json it was also trying to export one simultaneously
- Removes the hacky forced page refresh in favor of deep merging existing state with the incoming json
=> fix: importing

server/src/services/logUserAuth.js
If logChannelHidePii is set to true do not fetch geo data from ip-api.com
=> Not fetch geo data if hidepii is true

packages/types/lib/scanner.d.ts, server/src/graphql/typeDefs/scanner.graphql, server/src/models/Gym.js, src/features/gym/GymPopup.jsx, src/services/queries/gym.js
Needs https://github.com/UnownHash/Golbat/pull/217.
=> feat: add support for guarding_pokemon_display

packages/locales/lib/human/ja.json
I've made some corrections where things felt off.
=> Update Japanese localization

server/src/index.js, src/components/auth/Telegram.jsx
Adding script and frame src for telegram helped
=> Fixes telegram login widget

packages/logger/lib/tags.js, packages/types/lib/general.d.ts, packages/types/lib/server.d.ts, server/src/configs/local.example.json, server/src/graphql/resolvers.js, server/src/graphql/server.js, server/src/middleware/apollo.js, server/src/middleware/logger.js, server/src/models/Weather.js, server/src/services/AuthClient.js, server/src/services/DataLimitCheck.js, server/src/services/DiscordClient.js, server/src/services/Stats.js, server/src/services/TelegramClient.js, server/src/services/api/scannerApi.js, server/src/services/functions/getBbox.js, server/src/services/functions/getCenter.js, server/src/services/functions/getClientTime.js, server/src/services/functions/getPlacementCells.js, server/src/services/functions/getTypeCells.js, server/src/services/state.js, src/features/search/useSendSearch.js
This refactors and consolidates a lot of the various caches that were previously stored around the project into a new `Stats` class, which will be used in the future for tracking other stats as well. I don't believe there are any direct changes in this PR, just a lot of tidying up and internal API simplifying.
=> refactor: caches / stats

package.json, vite.config.js, yarn.lock
Replaces the old react plugin with the new swc plugin, compiles the client ~2x as fast.
=> refactor: react-swc vite plugin

server/src/services/LocalClient.js, server/src/strategies/local.js
This updates the `local` strategy to extend the `AuthClient` class so it is more in line with the `Discord` and `Telegram` strategies.
=> refactor: local strategy

packages/types/lib/scanner.d.ts, src/features/gym/GymPopup.jsx
Gym defender will properly show reverted form after mega/primal evolution finishes.
=> fix: properly support gym defender temp evolutions

packages/locales/lib/human/en.json, server/src/ui/clientOptions.js, src/components/dialogs/Footer.jsx, src/components/dialogs/UserOptions.jsx, src/features/drawer/components/CollapsibleItem.jsx, src/store/useStorage.js, src/store/useWebhookStore.js
This sorts and displays categories in each of the Options menus for each category. Making it much less overwhelming to use. Based on #1050
=> feat: categories in options menus

packages/types/lib/scanner.d.ts, src/features/gym/GymPopup.jsx, src/features/pokestop/PokestopPopup.jsx, src/services/Assets.js
Needs https://github.com/UnownHash/Golbat/pull/216.
=> feat: support pokemon display in showcases

README.md, server/src/models/Station.js
needs testing / feedback from others ... here it seems to work
=> fix: display only available stations / dynaraids

server/src/graphql/resolvers.js
=> fix: search while not logged in

server/src/filters/builder/pokemon.js, server/src/models/Pokestop.js, src/hooks/useTranslateById.js
=> fix: do not set unset form on quest pokemon without display

packages/types/lib/server.d.ts, server/src/models/Gym.js, server/src/models/Nest.js, server/src/models/Pokestop.js, server/src/models/Portal.js, server/src/models/Station.js, server/src/services/DbManager.js
- fixes search
- fixes hiding old pokestops (switch wasn't used)
- small MAD remainings cleanup
Thanks @ReuschelCGN !
=> Fix: Search, old pokestops, small cleanup
