- client/src/components/MapTiles.jsx
- client/src/components/devices/Device.jsx
- client/src/components/devices/MarkerIcon.js
- client/src/components/devices/Popup.jsx
- client/src/components/gyms/Gym.jsx
- client/src/components/pokemon/Pokemon.jsx
- client/src/components/pokestops/Pokestop.jsx
- client/src/services/Query.js
- client/src/services/data/device.js
- server/src/models/Device.js
- server/src/models/index.js
- server/src/schema/device.js
- server/src/schema/schema.js
- Add Device Support
- Slight refactoring
> Add Devices

- client/package.json
- client/src/components/MapTiles.jsx
- client/src/components/pokestops/Pokestop.jsx
- client/src/components/portals/Popup.jsx
- client/src/components/portals/Portal.jsx
- client/src/components/weather/Popup.jsx
- client/src/components/weather/Weather.jsx
- client/src/components/weather/marker.js
- client/src/data/weatherTypes.json
- client/src/services/Query.js
- client/src/services/data/weather.js
- client/src/services/getPolygon.js
- client/src/services/getPolyline.js
- client/webpack.config.js
- server/src/models/Weather.js
- server/src/models/index.js
- server/src/schema/schema.js
- server/src/schema/weather.js
- yarn.lock
- Fix weather implementation
- Polylines instead of polygons
- Fix up webpack
- Fix getting correct cell IDs
- Remove unnecessary packages
> Add weather

- client/src/components/MapTiles.jsx
- client/src/components/gyms/Gym.jsx
- client/src/components/layout/Drawer.jsx
- client/src/components/pokemon/Pokemon.jsx
- client/src/components/pokestops/Pokestop.jsx
- client/src/components/portals/Portal.jsx
- client/src/components/s2Cell/S2Cell.jsx
- client/src/components/spawnpoints/Spawnpoint.jsx
- client/src/components/submissionCells/Popup.jsx
- client/src/components/submissionCells/SubmissionCells.jsx
- client/src/components/submissionCells/data/Ring.js
- client/src/components/submissionCells/data/getPlacementCells.js
- client/src/components/submissionCells/data/getTypeCells.js
- client/src/components/submissionCells/placementStyle.js
- client/src/components/submissionCells/typeStyle.js
- client/src/components/weather/Weather.jsx
- client/src/services/Query.js
- client/src/services/data/submissionCells.js
- Add ability to see submission cells
- Refactor bounds variable
> Add Submission Cells

- server/src/models/Gym.js
- server/src/models/Pokestop.js
- server/src/schema/pokestop.js
- src/components/markers/quest.js
- src/components/popups/Gym.jsx
- src/components/tiles/Pokestop.jsx
- src/services/queries/pokestop.js
- If a user wants to see specific rockets and specific quests, rockets will no longer show quests if they are not included in the list of desired quests.
- Example: a user has ultra balls and fire type rockets on. If a stop has a fire type rocket and an ultra ball, it will show both, otherwise it will only show the fire rocket. No pokeballs, pinaps, etc.
> Only Show Requested Data

- README.md
- package.json
- server/src/configs/config.example.json
- server/src/configs/default.json
- server/src/index.js
- server/src/models/Gym.js
- server/src/models/Pokestop.js
- server/src/routes/rootRouter.js
- server/src/services/Utility.js
- server/src/services/defaultFilters/buildDefaultFilters.js
- server/src/services/functions/fetchJson.js
- server/src/services/functions/fetchQuests.js
- server/src/services/functions/fetchRaids.js
- server/src/services/generateMasterfile.js
- src/services/functions/menuFilter.js
- Add config options to skip querying db in favor of fetching active quests/invasions/raid bosses from Pogo Info repo
- Add check to fetch these repos if the db query returns empty (at night when Raids end or if quests are cleared due to a reroll)
- Compares invasions and returns latest if new lineups are available
- Change startup scripts to generate the masterfile at restart
- Update readme
Thanks @ccev
> Make available optional

- server/src/configs/default.json
- server/src/services/defaultFilters/buildDefaultFilters.js
- src/components/layout/drawer/Areas.jsx
- src/components/layout/drawer/Drawer.jsx
- src/components/layout/drawer/WithSubItems.jsx
- Removes a check that required the areas.json file, even if you were using manual areas
- Makes the "enabled" button optional via the config. If you are only using the manual areas, this switch does nothing, so it's best to disable it entirely so you don't confuse users. 
- If you are using manual areas for the list but still want to use your areas.json for the overlay, then leave this new config option false.
> Areas.json optional

- README.md
- public/base-locales/en.json
- src/assets/mui/theme.js
- src/assets/scss/main.scss
- src/components/layout/dialogs/filters/SlotSelection.jsx
- src/components/layout/drawer/WithSliders.jsx
- src/components/popups/Gym.jsx
- src/components/popups/Pokemon.jsx
- src/components/popups/Pokestop.jsx
- Reduces the footprints of timers
- Fixes timers from not being able to toggle
- Reduces the footprint of the accordions
- Adds a couple of missing translation keys
- Timers can be toggled
- Update readme
- Reverses Gym Slot for better grammar
- Fixes Raid bosses not being translated
> Timer CSS/Toggle & Mui Overrides

- public/base-locales/fr.json
- server/src/configs/default.json
- src/components/Clustering.jsx
- src/components/Map.jsx
- src/components/QueryData.jsx
- src/components/markers/gym.js
- src/components/markers/pokestop.js
- src/components/tiles/Gym.jsx
- src/components/tiles/Pokestop.jsx
Adds advanced config options to allow offsetting the raid boss/egg on gym marker, and the quest reward on pokestop marker.
This gives option to replace the icon set and have markers nicely arranged.
Example with :
```
"iconModifiers": {
"gyms": {
"offsetX": 0.2,
"offsetY": 0.3
},
"pokestops": {
"offsetX": 0.2,
"offsetY": 0.1,
"sizeMultiplier": 0.7
}
}
```
> Add option to offset raid boss/egg/quest rewards on markers

- server/src/configs/config.example.json
- server/src/configs/default.json
- server/src/db/initialization.js
- server/src/models/Device.js
- server/src/models/Gym.js
- server/src/models/Nest.js
- server/src/models/Pokemon.js
- server/src/models/Pokestop.js
- server/src/models/Portal.js
- server/src/models/S2cell.js
- server/src/models/Spawnpoint.js
- server/src/schema/schema.js
- server/src/services/areas.js
- server/src/services/discord.js
- server/src/services/functions/getAreaSql.js
Adds SQL Area Restrictions for:
- Devices
- Gyms
- Nests
- Pokemon
- Pokestops
- S2 Scan Cells
- Spawnpoints
- Unlimited number of rules can be set in the config
Partially authored by @Len for MapJS.
Co-Authored-By: Jakub <10072920+lenisko@users.noreply.github.com>
> SQL Area Restrictions

- .github/workflows/docker.yml
- .github/workflows/lint.yml
AKA fix the CI/CD failures
External forks can't push to this organization container registry.
Github does this for security reasons. Running the test cases are nice
so they have been moved to the lint workflow.
More information: https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
> Don't push forked repos to docker package container

- webpack.config.js
`ESLintPlugin` slows down `yarn start` by 3x, wasting CPU cycles and time while achieving absolutely nothing. We should disable it at least for end users.
> Remove ESLintPlugin

- src/components/popups/Gym.jsx
- src/components/tiles/Gym.jsx
- src/services/Utility.js
- src/services/functions/formatInterval.js
- src/services/functions/getTimeUntil.js
* Egg timer tooltip now displays correctly.
* 3:00 will display as `3m` instead of `3m 0s`.
* Display raid duration when both start timer and end timer is on screen.
> Refine raid timers

- server/src/routes/rootRouter.js
- src/components/Auth.jsx
- Previously grey screened if `map` was not included in the `alwaysAvailable` array but other perms were.
- Now redirects to login page if it's missing
> Fixes grey screen if map is not included

- src/components/tiles/Pokemon.jsx
This change will make it possible to always some 100 IV (Hundos) on Top of all other pokémon on the map. Before the hundo could hide behind other pokémons.
> Fix Hundo on Top

- server/src/configs/default.json
- src/components/popups/Pokestop.jsx
- src/components/tiles/Pokestop.jsx
- Message comes straight from config, write in your own locale
- Lets you send a reminder whether a quest requires an AR task or not
- Meant to tide scanners over until the AR situation is stabilized
> Adds Quest Message

- server/src/models/Filters.js
- server/src/services/ui/primary.js
Unfortunately, at least for now, this has to be server side/configured by the admin in order to stay in sync with the server when requesting data
- Set min rank (defaults to 0)
- Set max rank (defaults to 100)
Settings found in database => settings 
```json
"leagues": [
{
"name": "great",
"cp": 1500,
"maxRank": 150
},
{
"name": "ultra",
"cp": 2500,
"minRank": 5
},
{
"name": "little",
"cp": 500,
"minRank": 10,
"maxRank": 150
}
],
```
Great defaults to a min of 1 and sets the max to 150
Ultra sets the min to 5 and defaults to a max of 100
Little is set to 10 - 150
> Min & Max PVP Ranks

- server/knexfile.cjs
- server/src/configs/default.json
New config value:
```json
"migrationTableName": "knex_migrations",
```
Call it whatever you want if you have other applications (like Poracle) that use Knex to handle migrations and reduce interference.
> Add Custom Migration Table Name

- docker-compose.example.yml
when introducing "yarn migrate:latest" into docker missed the "yarn start" part, it was only command "start", sorry for that.
> fixes docker-compose example

- public/base-locales/en.json
- src/components/layout/dialogs/webhooks/WebhookAdv.jsx
- src/services/Poracle.js
- Locale fix for slot_changes when displaying in the Poracle string
- Better descriptions for some of the categories in the tracked views
- Adds support for showing only existing movesets on Raid bosses, rather than all of them
> Poracle Fixes & Better Movesets

- server/src/models/Pokestop.js
- server/src/schema/pokestop.js
- src/components/popups/Pokestop.jsx
- src/services/queries/pokestop.js
- Adds support for quest titles if parsed by the backend, currently only MAD supports
- Uses game assets to natively translate the quest text into every locale supported by pogo, providing a 1:1 experience for users
> Native MAD Quest Titles

- server/src/configs/default.json
- server/src/services/config.js
- src/components/layout/Nav.jsx
- src/components/layout/auth/Login.jsx
- src/components/layout/custom/CustomTile.jsx
- src/components/layout/custom/Generator.jsx
- src/components/layout/dialogs/DonorPage.jsx
- src/components/layout/dialogs/Motd.jsx
- Migrate MotD to use a "components" array instead of "messages", to align with the other custom config objects
- Automatically migrates in RAM but needs to be renamed in the config manually
> Migrate MotD

- .gitignore
- src/services/Fetch.js
- src/services/Icons.js
- Supports local folders
- Put the folder in the `public/images/uicons` folder
- Json index file must be in the root of each folder you have in the `uicons folder`
- See below example for substituting local over remote
```json
{
"name": "Default",
// uses remote
"path": "https://raw.githubusercontent.com/WatWowMap/wwm-uicons/main/",
// uses local
"path": "wwm-uicons",
"modifiers": {
"gym": {
"0": 1,
"1": 1,
"2": 1,
"3": 3,
"4": 4,
"5": 4,
"6": 18,
"sizeMultiplier": 1.2
}
}
},
```
> Local UICONS

- server/src/routes/rootRouter.js
Makes that a permission listed in the `alwaysEnabledPerms` array is always enabled, if there is an authentication method activated or not, if user is logged or not, like **always enabled**.
> Fix alwaysEnabledPerms logic

- server/scripts/configMigration.js
- server/src/configs/default.json
- server/src/configs/local.example.json
- server/src/models/Gym.js
- server/src/models/Nest.js
- server/src/models/Pokemon.js
- server/src/models/Pokestop.js
- server/src/models/Portal.js
- server/src/models/ScanCell.js
- server/src/models/Spawnpoint.js
- server/src/services/checkForUpdates.js
- server/src/services/config.js
- Query limits for Gyms, Nests, Pokemon, Pokestops, Portals, ScanCells, and Spawnpoints
- Due to PVP filtering being done in JS compared to SQL, I caution against setting Pokemon too low
- checkForUpdates adds instruction updates to console
- Re-introduction of noScanAreaOverlay to config
- packageSource added to config
> Add Query Limits

- server/src/configs/default.json
- src/components/layout/FloatingBtn.jsx
- src/components/layout/Nav.jsx
Adds a Profile shortcut to main page when logged In and this enabled in `local.json` > `map` > `misc` > `"enableFloatingProfileButton": true,` (default to `false`)
> Adds option for Floating Profile Button

- public/base-locales/fr.json
- src/components/layout/auth/Login.jsx
> Correct Scrolling Issue

- server/src/services/api/resolveQuickHook.js
- server/src/services/initWebhooks.js
- server/src/services/ui/webhook.js
Requires Poracle PR676, might work without it also, I didn't test it.
Hides In battle switch from gym alarm selection and based on the value received alters the quick add gym alarm -functionality.
I guess it's still possible for users to inject the `battle_changes` flag from frontend, but that isn't a major concern.
And again a warning, I still learning JS, so make sure this makes sense!
> Read gymBattles flag from Poracle and act accordingly

- server/src/routes/rootRouter.js
- Works if you put the "none" role in the area restriction "roles" array
- Addresses #404
> Enable Area Restrictions for Unauthenticated

- .gitignore
- esbuild.config.mjs
- src/index.jsx
- src/services/i18n.js
**== This PR adds a feature that will never be officially supported ==** 
- Don't like my implementation?
- Too lazy to write a configurable PR?
- Want to maintain custom files while keeping it git friendly?
This PR enables you to replace every single file in the root `src` folder with your own implementation!
For example, if you want to customize the Pokestop marker:
1. Copy `src/components/markers/pokestop.jsx`
2. Name new file to `src/components/markers/pokestop.custom.jsx`
3. Make your changes
4. Recompile
5. Celebrate that you're no longer limited to my opinions and praise how generous I am
**F.A.Q.**
Q. But Turtle, why would I want to write a custom component instead of relying on the config? 
-  The config is massive and overwhelming at this point. Most of the options only cater to …
> Proper Custom Code Injection

- server/scripts/console.js
- server/src/configs/default.json
- server/src/configs/local.example.json
- server/src/db/initialization.js
- server/src/graphql/context.js
- server/src/graphql/resolvers.js
- server/src/graphql/scannerTypes.js
- server/src/index.js
- server/src/models/Badge.js
- server/src/models/Device.js
- server/src/models/Gym.js
- server/src/models/Nest.js
- server/src/models/Pokemon.js
- server/src/models/Pokestop.js
- server/src/models/Portal.js
- server/src/models/ScanCell.js
- server/src/models/Spawnpoint.js
- server/src/models/Weather.js
- server/src/models/index.js
- server/src/routes/rootRouter.js
- server/src/services/DbCheck.js
- src/components/Clustering.jsx
- src/components/popups/Device.jsx
- src/components/tiles/Nest.jsx
- src/services/queries/device.js
- src/services/queries/nest.js
- Auto database detection type (mad/rdm)
- Auto detects certain DB configurations such as PVP V2, Multiple Invasions, amount column, alternative quests, etc
- Now binds models for every category on every database (multiple databases for things like devices, quests, etc)
- Handles deduping results when querying a category from multiple databases
- Now handles ohbem init
- New methods for all GQL resolvers
- Now queries available at startup instead at every session init, and updates every 1 hr (configurable)
- Uses amount columns to rapidly increase quest querying and searching
- Supports RDM multiple invasions https://github.com/RealDeviceMap/RealDeviceMap/pull/326
- User/Badge/Session models (ie, all ReactMap tables) can still only have 1 connection/table, for obvious reasons
**I really …
> Better Database Management

- src/components/layout/custom/CustomButton.jsx
- src/components/layout/custom/CustomText.jsx
- src/components/layout/dialogs/Motd.jsx
- src/services/Utility.js
Ability to support multiple languages for custom components such as motd, login, and donor page
Example implementation:
```json
"content": {
"de": "Some German",
"en": "Some English"
},
```
Falls back to first language in the object if the user is using a language that isn't accounted for.
Resolves #281
> Locale Support for Custom Components

- server/src/models/Pokemon.js
- src/components/Map.jsx
- src/components/tiles/Device.jsx
- src/components/tiles/Gym.jsx
- src/components/tiles/Pokemon.jsx
- src/components/tiles/Pokestop.jsx
- src/components/tiles/Spawnpoint.jsx
- Set best rank correctly, ignores unrequested ranks
- Fixes some rendering issues by setting keys to check all icons and settings at a larger level - guaranteeing re-renders when necessary and saving performance on memoized marker renders
- Resolves #357
> Fix Pvp Rank Filtering

- src/assets/css/main.css
Fixes the issue with the floating menu buttons being overlapped by leaflet layers on iOS15.x devices
> iOS15.x floating menu button css fix

- package.json
- server/src/graphql/scannerTypes.js
- server/src/models/Device.js
- src/components/popups/DevicePoly.jsx
- src/services/queries/device.js
- Fix leveling instances
- Account for other uncommon circle instances
- Add 'radius' to gql api
- Version bump
> Fix Device Paths

- public/base-locales/en.json
- server/src/configs/default.json
- server/src/services/ui/clientOptions.js
- src/components/Errors.jsx
- src/components/QueryData.jsx
- src/components/layout/dialogs/UserOptions.jsx
- src/components/layout/general/ActiveWeather.jsx
- Zoomed in weather icon is now clickable
- Toggleable in the weather user options
- Defaults to false
- Also fixes the error page redirect
- Addresses #470
> Clickable Weather

- server/src/configs/default.json
- server/src/index.js
- server/src/models/Pokestop.js
- server/src/services/DbCheck.js
- server/src/services/EventManager.js
- server/src/services/api/fetchQuests.js
- server/src/services/initialization.js
- Remove the need for startup delay and retry count
- Ensure that db checks complete before the event promises start
- Move all of the db checks into one fn
- Some better fallbacks as well
- Less hacky db detection using `columnInfo()`
> Less Hacky Startup

- server/src/configs/custom-environment-variables.json
- server/src/configs/default.json
- server/src/models/Gym.js
- server/src/services/EventManager.js
- server/src/services/defaultFilters/buildDefaultFilters.js
- server/src/services/defaultFilters/buildGyms.js
- server/src/services/defaultFilters/buildPokemon.js
- server/src/services/defaultFilters/buildPokestops.js
- src/components/Container.jsx
- src/components/Map.jsx
- src/components/ReactRouter.jsx
- src/components/layout/auth/Auth.jsx
- src/hooks/useConfig.js
- src/hooks/useGenerate.js
- src/hooks/useRefresh.js
- src/hooks/useStore.js
- Fix some rendering issues on client side
- Add some configurable values for generating all possible desirable filters
- Add some more available-based filter generation as a backup
- Query for teams/slots during gym available
- Don't set event timers if querying upon session init
> Render refinement

- server/src/models/Pokestop.js
Addresses #485
errr wow git, this was only like 3 lines and a bunch of white space changes...
Can someone with MAD test this to make sure it's still fine?
> Fix Missing Alt Quests

- server/src/configs/custom-environment-variables.json
- server/src/configs/default.json
- server/src/services/DbCheck.js
- server/src/services/initialization.js
- src/components/layout/dialogs/Search.jsx
In search box the distance to a point is displayed in miles even though the unit says km. Instead of fixing that to either of the units, I added `distanceUnit` in config so admins can select which ever they prefer. I guess the most optimal would be to have it possible for users to select their preferred unit but making that happen was way beyond my skill level.
> Added distance unit selector

- server/src/configs/custom-environment-variables.json
- server/src/configs/default.json
- server/src/routes/rootRouter.js
- src/components/QueryData.jsx
- All categories are now configurable in config.api.polling
- Unit in seconds
- Falls back to 10s
> Configurable polling

- package.json
- src/index.jsx
- src/services/Utility.js
- yarn.lock
As google is stopping support for UA (Universal Analytics) by the end of the year, time has come to move to GA4.
Tested and working on my own instance.
> Add Support for Google Analytics 4

- .vscode/extensions.json
- server/src/models/Gym.js
- server/src/services/DbCheck.js
- Updates SQL query to use a dynamic column name based on a startup check
- Maintains backwards compatibility for older RDM clients that are still using availble_slots
> Available Slots Compatibility

- server/src/services/DiscordClient.js
- server/src/services/functions/scannerPerms.js
- server/src/services/logUserAuth.js
- Log user perms in Discord for additional troubleshooting/viewing
- Cleanup some scanner related perms
> Log User Perms in Discord

- server/src/configs/areas.example.json
- server/src/configs/custom-environment-variables.json
- server/src/configs/default.json
- server/src/configs/local.example.json
- server/src/graphql/mapTypes.js
- server/src/graphql/resolvers.js
- server/src/graphql/typeDefs.js
- server/src/routes/rootRouter.js
- server/src/services/api/fetchJson.js
- server/src/services/config.js
- src/components/QueryData.jsx
- src/components/layout/drawer/Areas.jsx
- src/components/layout/drawer/Drawer.jsx
- src/components/layout/drawer/WithSubItems.jsx
- src/components/tiles/ScanArea.jsx
- src/services/Query.js
- src/services/queries/scanAreas.js
- Normalize manual areas
- Add parents property support
- Fix instanceof error
When using with an areas.json file, just add the parent name to the properties of the child feature/area, next to the name, etc. 
When using manualAreas in the config, just add a parent property at the same level as the name/lat/lon/zoom.
You do not need an area/feature with the same parent name if you don't want it to be clickable.
> Expand Scan Areas List

- package.json
- server/src/models/ScanCell.js
- server/src/models/Weather.js
- server/src/services/config.js
- server/src/services/functions/getPlacementCells.js
- server/src/services/functions/getPolyVector.js
- server/src/services/functions/getTypeCells.js
- src/services/queries/portal.js
- src/services/queries/scanCell.js
- yarn.lock
- Weather now respects area restrictions / userArea selections with checking if the polygons overlap or are contained within each other
- getPolyVector now returns a reverse for geojson format as well
- Added scanAreasObj to config for easy ref
- Fix a couple of gql endpoints
Solves #489 as far as I'm concerned
> Weather Area Restrictions

- server/src/configs/default.json
- server/src/routes/rootRouter.js
- server/src/services/DbCheck.js
- server/src/services/EventManager.js
- server/src/services/functions/getAreaSql.js
- Wasn't updating cache for gql frontend to grab when queryOnSessionInit was enabled
- Lower default values for when it queries
- Enable raids by default now to query on session init since it's low cost
- Add optional logging to getAvailable method
> Fix Available Cache Issue

- server/src/graphql/resolvers.js
- src/components/layout/drawer/AreaTile.jsx
- src/components/layout/drawer/Areas.jsx
- src/hooks/useStore.js
- Create AreaTile.jsx to cleanup some code
- Add a reset button
- Add select all/none for parents
- Refine the add/remove state setter and cleanup any dead areas
> More Scan Area Refinement

- server/src/configs/default.json
- server/src/configs/local.example.json
- server/src/graphql/resolvers.js
- server/src/models/Weather.js
- server/src/services/areas.js
- server/src/services/config.js
- server/src/services/functions/getAreaSql.js
- src/components/layout/drawer/AreaTile.jsx
- src/components/layout/drawer/Areas.jsx
- src/components/tiles/ScanArea.jsx
- src/hooks/useStore.js
- Add multiDomain and hidden support to manual areas
- Maintain hidden areas for areaRestriction purposes but still hide them from the map and sidebar menu
- Add a check in weather model to fix an edge case
- *Allow* manualAreas and an areas.json to be used together
- Fix reset button
- Fix sidebar menu grid items when the name is too long, assuming it's a multi-word name
- Less hacky ScanArea tile stuff
> Scan Area Filtering Refinements

- server/scripts/generateMasterfile.js
- server/src/configs/custom-environment-variables.json
- server/src/configs/default.json
- server/src/index.js
- server/src/services/DbCheck.js
- server/src/services/EventManager.js
- src/components/layout/drawer/AreaTile.jsx
- Rerun historical rarity every 6 hours by default
- Cleanup some code in DbCheck class
- Check for strings in both hash maps
- Fix some spacing issues in scanAreas menu
- Add another disable check to the checkbox in scanAreas menu
> Add historical rarity to the event loop

- public/base-locales/en.json
- server/src/configs/custom-environment-variables.json
- server/src/configs/default.json
- server/src/services/ui/clientOptions.js
- src/components/tiles/ScanArea.jsx
- Client side option to toggle whether area polygons are selectable when tapping/clicking on them on the map
> Tap to toggle option

- src/components/layout/dialogs/Search.jsx
- src/components/popups/Pokemon.jsx
- src/components/popups/Pokestop.jsx
- src/components/popups/common/NameTT.jsx
- src/components/popups/common/TimeTile.jsx
Tooltips for...
- Quest searching
- Nest searching
- Raid searching
- Pokemon PVP
- Invasions
- Invasion lineups
- Lures
- Quest rewards
Resolves #542
> Various Tooltips

- server/src/models/Pokestop.js
- server/src/services/DbCheck.js
- Checks to see whether the new `layer` column exists
- Selects it as `with_ar` for easy compatibility with existing code
- Backwards compatible
**Need to test with MAD and RDM**
> Support MAD Layer Column

- src/components/markers/pokemon.jsx
- src/components/tiles/Pokemon.jsx
A marker for for mons found in nearby cells so users can see right away that their location isn't accurate.
I didn't quite understand the current calculation for icon placement when accounting for the pokemon icon offsetX so I just set the position to fixed 10%.
> Added a grass icon for Pokemon found in nearby cells

- server/src/configs/custom-environment-variables.json
- server/src/configs/default.json
- server/src/models/Pokestop.js
- src/components/markers/pokemon.jsx
- src/components/tiles/Pokemon.jsx
- Remove hideOldQuests from config
- Also remove joinGymBadgeTable since it's not used anymore
> always hide old quests

- src/services/Icons.js
Hello,
I noticed that the Pokémon icons didn't work with shinies. According to the [UIcons specifications](https://github.com/UIcons/UIcons#pokemon-icons), the shiny flag is `_s` and not `_shiny`. Even though this flag is only provided on quest rewards icons, this function might be used by custom components. 
Thanks.
> fix Pokemon icon not working with shinies

- package.json
- server/src/configs/custom-environment-variables.json
- server/src/configs/default.json
- server/src/graphql/mapTypes.js
- server/src/graphql/scannerTypes.js
- server/src/models/Pokestop.js
- server/src/services/defaultFilters/buildPokestops.js
- server/src/services/ui/advMenus.js
- src/assets/css/main.css
- src/components/ErrorBoundary.jsx
- src/components/layout/dialogs/Search.jsx
- src/components/markers/pokestop.jsx
- src/components/popups/Device.jsx
- src/components/popups/Gym.jsx
- src/components/popups/Nest.jsx
- src/components/popups/Pokemon.jsx
- src/components/popups/Pokestop.jsx
- src/components/popups/Portal.jsx
- src/components/popups/ScanCell.jsx
- src/components/popups/Spawnpoint.jsx
- src/components/popups/SubmissionCell.jsx
- src/components/popups/Weather.jsx
- src/components/tiles/Device.jsx
- src/services/Icons.js
- src/services/Utility.js
- src/services/filtering/genPokestops.js
- src/services/functions/getRewardInfo.js
- src/services/functions/parseConditions.js
- src/services/queries/pokestop.js
- src/services/queries/search.js
- Adds proper support for filtering XP amounts
- Builds 100 - 1000 by default
- MAD support is pending schema review
- Bump to version 1.4.0
> Full XP Filtering Support

- server/src/configs/custom-environment-variables.json
- server/src/configs/default.json
- server/src/services/DbCheck.js
- server/src/services/sessionStore.js
- wrap a couple of async functions in try/catch blocks
- fix mysql session for mysql2 bindings
- Add config value for session check interval
> Add a couple of try catches

- server/src/services/config.js
- Allow `messageOfTheDay.json`, `loginPage.json`, and `donationPage.json` in the config folder
- Works with multiDomains by adding a folder and named jsons instead: `server/src/configs/loginPage/subDomain_1.json`
`server/src/configs/loginPage/subDomain_2.json`
Resolves #574
> Extract Config Pages

- server/src/routes/api/v1/sessions.js
- server/src/routes/api/v1/users.js
- Add Discord and Telegram endpoints by ID
- Add feedback if no user is found
> Update user api

- .gitignore
- server/src/configs/custom-environment-variables.json
- server/src/configs/default.json
- server/src/index.js
- server/src/routes/api/v1/config.js
- server/src/services/sessionStore.js
- Allows admins to fetch their config so they can see the full config after the merges and mutations have been applied
- Configurable options to include the schemas and authentication strategies for security reasons
- Minor change in sessionStore.js to allow running the map server without any db connections
- Accessible at `https://my_map_url.com/api/v1/config` with your react-map-secret of course
> Add a config api route

- package.json
- public/index.html
- src/assets/css/holiday.css
- src/assets/css/loading.css
- src/components/Config.jsx
- For some reason I needed to move the holiday-canvas div to the html template instead of in React...
- Reported by @ReuschelCGN
- Also lints html/css files, oops
> Fix Holiday Animations

- package.json
- server/src/configs/custom-environment-variables.json
- server/src/configs/default.json
- server/src/services/config.js
- src/components/Config.jsx
- src/components/HolidayEffects.jsx
- src/services/HolidayAnimations.js
- Rude config change, `holidayEffects` is now an array of objects instead of an object with bool properties
```ts
interface HolidayObject {
name: string // does nothing other than label in config
enabled: boolean
images: string[]
css: 'snow' | 'fireworks'
startDay: int
startMonth: int
endDay: int
startDay: int
}
```
- Enables any amount of images to be put into the effects as well as any amount of custom holiday effects
> holiday effects v2

- package.json
- server/src/configs/default.json
- server/src/graphql/resolvers.js
- server/src/index.js
- server/src/services/Clients.js
- server/src/services/DiscordClient.js
- server/src/services/Fetch.js
- server/src/services/api/scannerApi.js
- server/src/services/logUserAuth.js
- server/src/strategies/discord.js
- server/src/strategies/local.js
- server/src/strategies/telegram.js
- src/components/layout/dialogs/scanner/ScanOnDemand.jsx
**Important**
- REQUIRES ADJUSTMENTS IF YOU USE A CUSTOM STRATEGY, see the changes to the files in `server/src/strategies` 
**Other notes**
- Version bump
- Add thumbnailUrl to discord strategy object
- pass full req.user to scanner api
- Initialize strategies in a separate file for dynamically collecting all clients
- Rudimentary cache for storing # of requests for users in a given day
- Log to the same channel as authentication reqs
- Remove unused accessToken arg
- Save logChanneld in the class instance
- Remove user info from frontend, collect from request instead
> Scan Next/Zone Discord Logging

- .github/workflows/config.yml
- .github/workflows/docker.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- `tj-actions/changed-files` v19 => v33
- `actions/checkout` v2 => v3
- `actions/setup-node` v2 => v3
- `docker/build-push-action` v2 => v3
- `docker/metadata-action` v3 => v4
- `docker/login-action` v1 => v2
- only run yarn update env config script if the file has changed
- minor formatting fixes
> Bump Versions for GH Actions

- server/src/services/DiscordClient.js
- server/src/services/logUserAuth.js
There are more elegant ways to fix this but its a fix.
> Discord max field size 1024 exceeded fix

- server/src/models/Pokestop.js
- src/components/popups/Pokestop.jsx
This should change the event stop query so that it includes all display types >= 7. Right now this only includes the Coin and Kacleon Stops. This is assuming that future event stops work the same way.
Untested
> Include Kacleon Stops in Event Stops

- package.json
- src/components/QueryData.jsx
- src/services/apollo/AbortableContext.js
- src/services/apollo/AbortableLink.js
- src/services/apollo/RobustTimeout.js
- src/services/apollo/index.js
- yarn.lock
Partially reverts https://github.com/WatWowMap/ReactMap/commit/a9c31310ac524622c39d98d7b4064540f3ac9a2c, a very mean commit that reverts #119. 💔
> Abortable context strikes back: apollo sucks ass

- src/services/apollo/AbortableContext.js
- src/services/apollo/RobustTimeout.js
Should fix the following issues:
* When the querydata is being created for the first time, the connection is not subject to timeout.
* When the query was aborted, the old data is being removed and an error pops out.
> Robust timeout v2

- ReactMap.js
- docker-compose.example.yml
- server/src/index.js
- server/src/services/areas.js
- server/src/services/config.js
- server/src/services/geocoder.js
- server/src/services/logger.js
- Adjust docker-compose example for clarity
- Force color level 3
- Make the main data log more informative
- Push the default uicons set when none are present, e.g. docker use
- Add some more colors for different endpoints
- Timer on server startup log animation
> Logging Adjustments & Docker Fixes

- package.json
- server/scripts/generateMasterfile.js
- server/src/index.js
- server/src/services/DbCheck.js
- server/src/services/filters/pokemon/Backend.js
- Replaces a couple of other places that previously used JS Maps with just plain objects, since they seem to be somewhat prone to memory leaks
- Fixes a log that was writing to a new line without a tag
- Fixes a jsdoc return type
> use plain objects

- public/base-locales/en.json
- server/src/routes/authRouter.js
- server/src/routes/clientRouter.js
- server/src/services/DiscordClient.js
- server/src/services/logUserAuth.js
- src/components/ReactRouter.jsx
- src/components/layout/auth/Blocked.jsx
Discord guild blocking has been broken for a while maybe since the MapJS port? It was never a major issue but the current implementation definitely doesn't look correct. Currently when a user attempts to sign-in and is included in a blocked Discord Guild they will return to the login page and no discord alert is ever sent.
<details>
<summary>
Server side error before this PR
</summary>
ℹ 2023-06-22 00:59:30 [EVENT] Added Spinda Key: 327-0 to masterfile. (pokestops)
Server is now listening at http://0.0.0.0:8060
Server is now listening at http://0.0.0.0:8060
⚠ 2023-06-22 00:59:41 [DISCORD] Failed to get perms for user 130865078219046915 TypeError: Cannot read properties of undefined (reading 'find')
at DiscordClient.getPerms (/Users/clayton/src/scanner/ReactMap/server/src/services/DiscordCl …
> User feedback on Discord guild blocking & no map access

- package.json
- server/src/graphql/resolvers.js
- server/src/graphql/scannerTypes.js
- server/src/models/Device.js
- server/src/models/Pokemon.js
- server/src/services/areas.js
- server/src/services/functions/consolidateAreas.js
- server/src/services/functions/filterRTree.js
- server/src/services/functions/getAreaSql.js
- src/components/tiles/Device.jsx
- src/services/queries/device.js
- Allow parents to work correctly with area restrictions
- Better function to consolidate areas from permissions and user set, shared between sql and rtree
- Filter with rtree with devices, since that was forgotten
- Change all device `last_lat` => `lat` and `last_lon` => `lon`
- Allow areas that have hidden set to true to still exist in the rtree
Resolves #619
> scan area fixes

- server/src/services/EventManager.js
- src/services/Icons.js
- Adds a backup object in case index fetching fails 
- Adds try/catch blocks to all uicons methods in the client, since this seems to be the most common crash and won't go away until github stops sucking
> uicons try/catch in browser

- package.json
- public/base-locales/de.json
- public/base-locales/en.json
- server/src/models/Gym.js
- server/src/models/Pokestop.js
- server/src/services/filters/builder/pokestop.js
- src/components/QueryData.jsx
- src/components/layout/dialogs/webhooks/WebhookAdv.jsx
- src/components/layout/drawer/WithSubItems.jsx
- src/components/popups/Pokestop.jsx
- src/services/Icons.js
- src/services/Poracle.js
- src/services/filtering/genPokestops.js
- split event stops into separate filters
- new collapse menu when enabling `Event Stops` in the drawer
- poracle support for `showcase`
- waiting for better backend support to fill in popup info before merge
> feat: individual event filtering

- server/src/models/Pokestop.js
- src/components/popups/Pokestop.jsx
- Exclude rocket pokemon from the pokestop popup
- Only ones that can actually be rewards
- Gradually hides the grunt type and different rocket pokemon rewards as you hide them, to help with clarity
- Fixes a filtering issue when using `only confirmed`
Resolves #685
> feat: exclude rocket pokemon

- src/components/markers/gym.jsx
- src/components/markers/pokemon.jsx
- src/components/markers/pokestop.jsx
- src/components/tiles/Pokemon.jsx
- src/services/functions/getOpacity.js
- Sets opacity of the marker based on the despawn time
- Active for pokemon, invasions, and raids
- Follows these rules:
- < 1 min = 25%
- < 5min = 50%
- < 10min = 75%
- More than 10min = 100%
- This does not interact with the marker memoization equality checks for performance reasons. In order to update opacity, you'll have to move the marker off screen and back again to rerender it
Resolves #683
> feat: interactive marker opacity

- public/base-locales/de.json
- public/base-locales/en.json
- public/base-locales/es.json
- public/base-locales/fr.json
- public/base-locales/it.json
- public/base-locales/ja.json
- public/base-locales/ko.json
- public/base-locales/nl.json
- public/base-locales/pl.json
- public/base-locales/pt-br.json
- public/base-locales/ru.json
- public/base-locales/sv.json
- public/base-locales/th.json
- public/base-locales/zh-tw.json
- server/src/services/Fetch.js
- src/components/popups/Gym.jsx
- src/hooks/useWebhook.js
- Allows you to remove gym, raid, and egg tracking from the gym popup menu if you're already tracking one, instead of only allowing you to add the same ones, even when you were already tracking it
Resolves #615
> feat: remove quick gym button for poracle

- package.json
- src/components/Map.jsx
- src/components/layout/dialogs/scanner/ScanOnDemand.jsx
- src/components/layout/dialogs/scanner/Shared.jsx
- src/hooks/useCooldown.js
- src/hooks/useStore.js
- externalizes the cooldown into a hook so it works even when scanNext/scanZone isn't open
- persists the cooldown state between refreshes, but only in localStorage. Technically this can be worked around if someone cleared local storage but that's incredibly tedious and I think unlikely that any user will be abusing it that way. Maybe long term we could add it server side but for now I'm not that worried about it.
> fix: scan on demand cooldowns

- src/components/Map.jsx
In https://github.com/WatWowMap/ReactMap/pull/580 map markers were disabled on scanZone feature due to performance issues. I think we're past these issues so we can bring markers back. 
I ran some tests locally on desktop and mobile and I hardly can see any difference when using map with markers or map with markers and scanZone on top
Btw I hope that's the only change that needs to be done ;)
> Bring back map markers when using scanZone

- server/src/models/Gym.js
- server/src/services/config.js
- src/components/layout/dialogs/UserProfile.jsx
- src/components/markers/gym.jsx
- src/components/popups/Pokemon.jsx
- Less opinionated for adding to `alwaysEnabledPerms`
- Better `http` replacing for fort images
- Gym edge case filtering
- Remove height and weight from Pokemon popup
> Minor text fixes

- src/components/layout/FloatingBtn.jsx
It was previously using the wrong prop name.
> fix: custom fab size name prop

- server/src/models/Pokemon.js
- server/src/services/DbCheck.js
- server/src/services/filters/pokemon/Backend.js
- server/src/services/filters/pokemon/constants.js
- server/src/services/functions/filterRTree.js
- server/src/types.d.ts
- No functionality changes, just jsdoc/type fixes
> Assorted jsdoc/type fixes

- server/src/models/Pokemon.js
- server/src/services/DbCheck.js
- server/src/services/logUserAuth.js
- server/src/types.d.ts
- Add `routes` permission to the discord auth log embed
- Fix and force typing in the `logUserAuth.js` file
- Cleanup types, somehow had a duplicate `Permissions` and `Perms` interface
Resolves #798
> fix: add routes to auth log

- src/components/Container.jsx
- src/components/ErrorBoundary.jsx
- src/components/Map.jsx
- src/components/layout/general/Notification.jsx
- src/components/tiles/Route.jsx
- src/components/tiles/ScanArea.jsx
- src/components/tiles/submissionCells/Ring.jsx
Solves a few bugs:
- When routes are enabled, sometimes when navigating to the login page from the map, then hitting the back button to go back to the map can cause the whole thing to crash. This is presumably a React leaflet bug 
- Some other navigation bugs related to panes
- Changes the behavior of the `ErrorBoundary` component to not hard crash, rather try to re-render the components first up to 5 times, similar behavior as Kōji.
> Leaflet bug fixes

- server/src/models/Pokestop.js
- server/src/models/Route.js
- server/src/services/functions/getAreaSql.js
This PR will allow people on MAD backend to display routes in RM
this PR needs to be tested by someone with a Golbat backend, to make sure it ain't breaking stuff there
it also needs to be tested by other MAD users
Fixes MAD support for event pokestops and also (I think) invasion filtering.
TLDR; MAD DB speaks datetime columns, and some of these are in UTC.
Also the model to get available events was out of order.
This should in theory work for any lost soul still running on legacy branch of MAD, but I only tested it on async.
> Route support for MAD db schema

- src/components/layout/custom/CustomButton.jsx
- src/components/layout/custom/CustomText.jsx
- src/components/layout/custom/CustomTile.jsx
- src/components/layout/custom/Generator.jsx
- src/components/layout/custom/LinkWrapper.jsx
- Deprecation of `href`, always use `link` - falls back for now
- Deprecation of `text`, always use `content` - falls back for now
- Deprecation of `localAuthUrl`, use `link` - falls back for now
- Adds support for `className` prop
If you are wanting to use a Discord login button, use `type: "discord"`, not a button type. These are preconfigured to make it easier for you!
> fix: custom components normalizing

- package.json
- packages/locales/lib/human/en.json
- server/src/index.js
- server/src/routes/rootRouter.js
- src/components/App.jsx
- src/components/ErrorBoundary.jsx
- src/components/layout/custom/CustomButton.jsx
- src/components/layout/custom/CustomImg.jsx
- src/components/layout/custom/CustomText.jsx
- src/services/Fetch.js
- src/services/Sentry.js
- vite.config.js
- yarn.lock
- Generates source map files during compiling
- Blocks them from being served
- Client sends the minified trace to the server, server parses it using the source maps, and logs a stack trace that's actually useful for finding bugs
- Also generates a UUID in the client to match with server logs
- Syncs with nginx using the `x-request-id` header
> feat: useful client error reports

- packages/locales/lib/human/de.json
Remove a duplicate admin translation in the German translation file.
[L65](https://github.com/sanderDijkxhoorn/ReactMap/blob/0b1e3b1429e2c08e66a1e8cdf357eef110c0d295/packages/locales/lib/human/de.json#L65) & [L671](https://github.com/sanderDijkxhoorn/ReactMap/blob/0b1e3b1429e2c08e66a1e8cdf357eef110c0d295/packages/locales/lib/human/de.json#L671)
> Remove duplicate admin key in de.json

- packages/locales/lib/human/de.json
fix poracle confirm_copy translation
Unfortunately the wording before was bit misleading. not it should be more clean.
When we click on the copy button we want to copy this profile to another. The text says pls choose a profile to copy to this.
@ReuschelCGN your thoughts?
> Update Poracle Translation DE and new ones

- server/src/configs/custom-environment-variables.json
- server/src/configs/default.json
- src/components/popups/Route.jsx
- src/components/tiles/Route.jsx
Hi!
In this PR, I added a button to download a route as a GPX file. This simply adds a button on the route popup to trigger the action.
Since this is a controversial feature, it's hidden behind a config. By default, it's disabled. To enable it, you need to set `map.misc.enableRouteDownload` to true. 
Thanks.
> Add route download

- src/components/popups/Gym.jsx
Small PR that adds the actual raid number to the gym popup if a user wants to know what proto # it is for adding to Poracle etc.
> feat: display raid level in popup

- server/src/models/Route.js
Raw query for MAD caused a double comparison ">" syntax in SQL which meant no routes where ever returned
#hacktoberfest
> Fix Routes in MAD

- package.json
- packages/locales/lib/human/en.json
- src/assets/css/main.css
- src/components/Clustering.jsx
- src/components/Config.jsx
- src/components/HolidayEffects.jsx
- src/components/layout/drawer/BoolToggle.jsx
- src/components/layout/drawer/Settings.jsx
- src/hooks/useStore.js
- src/services/functions/checkHoliday.js
- src/services/functions/setDeep.js
- yarn.lock
- Ditches terrible `react-leaflet-markercluster `lib in favor of custom implementation of the `supercluster` lib.
> feat: super cluster lib

- packages/locales/lib/human/en.json
- packages/types/lib/general.d.ts
- packages/types/lib/scanner.d.ts
- server/src/configs/default.json
- server/src/graphql/typeDefs/map.graphql
- server/src/graphql/typeDefs/scanner.graphql
- server/src/models/Gym.js
- server/src/models/PoI.js
- server/src/models/Pokestop.js
- server/src/services/filters/builder/base.js
- server/src/services/functions/getPlacementCells.js
- server/src/services/ui/clientOptions.js
- server/src/services/ui/primary.js
- src/components/layout/drawer/Extras.jsx
- src/components/tiles/submissionCells/S14Cell.jsx
- src/components/tiles/submissionCells/SubmissionCell.jsx
- src/services/queries/submissionCells.js
- Different color POI to indicate if it's a normal POI, a partner POI, or has had a showcase at any point
- Filter to include or not include partner POIs in the Wayfarer counts / POI display
- Two additional client side options to set the color for a partner or showcase POI
- `defaultFilters.submissionCells.includeSponsored`
- `clientSideOptions.wayfarer.showcaseColor`
- `clientSideOptions.wayfarer.partnerColor`
- `include_sponsored`
- `partner_color`
- `showcase_color`
Closes #870
> feat: Wayfarer enhancements

- packages/locales/lib/human/en.json
- src/components/Map.jsx
- src/components/layout/drawer/Settings.jsx
- src/hooks/useStore.js
- Adds a toggle (in dev mode only) to disable profiling logs if desired
> feat: toggle profiling logs (dev mode only)

- package.json
- src/components/Layers.jsx
- src/components/QueryData.jsx
- src/components/layout/auth/Login.jsx
- src/components/markers/usePokestopMarker.js
- src/components/tiles/Gym.jsx
- src/hooks/useOpacity.js
- src/hooks/useStore.js
- yarn.lock
- Fixes icon opacity for raids and invasions
- Removes one of the warnings from zustand about deprecated APIs
> fix: icon opacity and some zustand deprecated warnings

- server/src/configs/default.json
On an Android device it is possible to select the Tesla app as the default handler for Geo URIs.
This allows tapping on a link from your android device to trigger navigation in your Tesla without needing to go through another app and share the link again from there.
> Add GeoURI navigation option to defaults

- server/src/graphql/resolvers.js
- server/src/services/functions/getServerSettings.js
- src/components/Config.jsx
- src/components/layout/FloatingBtn.jsx
- src/components/layout/dialogs/scanner/ContextProvider.jsx
- src/components/layout/dialogs/scanner/Marker.jsx
- src/components/layout/dialogs/scanner/Popup.jsx
- src/components/layout/dialogs/scanner/ScanDialog.jsx
- src/components/layout/dialogs/scanner/ScanOnDemand.jsx
- src/components/layout/dialogs/scanner/Shared.jsx
- src/components/layout/dialogs/scanner/scanNext/PopupContent.jsx
- src/components/layout/dialogs/scanner/scanNext/getCoords.js
- src/components/layout/dialogs/scanner/scanNext/index.jsx
- src/components/layout/dialogs/scanner/scanZone/PopupContent.jsx
- src/components/layout/dialogs/scanner/scanZone/getCoords.js
- src/components/layout/dialogs/scanner/store.js
- src/components/layout/dialogs/scanner/useCheckValid.js
- src/hooks/useRefresh.js
- src/hooks/useStore.js
- Moves the client scanner storage to its own file, in a more appropriate folder
- Moves scanner cooldown property from `localStorage` to `sessionStorage`
- Also stores it in the cookie to deter it from easily being clearable with various checks to keep in sync
> refactor: scanner cooldown

- package.json
- packages/locales/lib/human/en.json
- packages/types/lib/scanner.d.ts
- server/src/graphql/typeDefs/scanner.graphql
- server/src/models/Pokestop.js
- src/assets/css/main.css
- src/components/markers/usePokestopMarker.js
- src/components/popups/Pokestop.jsx
- src/components/popups/common/TimeTile.jsx
- src/hooks/useOpacity.js
- src/services/queries/pokestop.js
This fixes how pokestops and their popups are displayed when there is a showcase present.
- Detects if a showcase exists server side
- Sends a new `hasShowcase` bool value to client
- Still shows other `incidents`/`kecleon` like events if a showcase is present, but in a disabled state with a TT that says why
> fix: pokestop with showcases

- src/components/layout/FloatingBtn.jsx
Changes from `error` color to `primary`, suppose there's no real reason to use error when the other buttons are disabled anyway.
Resolves #890
> fix: active scanNext/scanZone btns

- .eslintignore
- packages/config/package.json
- packages/locales/package.json
- packages/logger/package.json
- packages/masterfile/package.json
- packages/types/lib/config.d.ts
- packages/types/package.json
- src/components/layout/dialogs/Motd.jsx
uhh yeah, I guess this was broken, is no one using it? 😂 
(also fixes some npm commands and CI stuff)
> fix: motd index setter

- server/src/models/Pokestop.js
- server/src/services/DbCheck.js
:watwow: filters `enabled` and `deleted` in JS instead of SQL, this has improved general quest query times by 10x
Also made some optimizations to quest searching that improved performance substantially.
> perf: improve pokestop querying perf by 10x

- .gitignore
- packages/logger/lib/index.js
- packages/types/lib/config.d.ts
- server/src/index.js
- server/src/routes/api/v1/area.js
- server/src/services/DbCheck.js
- server/src/services/EventManager.js
- server/src/services/api/Poracle.js
- server/src/services/areas.js
- server/src/services/cache.js
- server/src/services/config.js
This rapidly increases the startup time of the server by caching all remote objects and loading them synchronously at startup instead of waiting for them asynchronously. The async functions to replace the cached with the live data still all run immediately following the startup of the server, this just now provides a much quicker startup time.
> feat: cache all remote data for quicker startup

- packages/types/lib/server.d.ts
- server/src/configs/default.json
- server/src/configs/local.example.json
- server/src/graphql/resolvers.js
- server/src/models/Pokestop.js
- server/src/services/DbCheck.js
- server/src/services/api/scannerApi.js
- server/src/services/cache.js
- server/src/services/filters/builder/base.js
- server/src/services/filters/builder/pokemon.js
- server/src/services/filters/builder/pokestop.js
- src/components/layout/dialogs/filters/OptionsContainer.jsx
- src/components/layout/drawer/Actions.jsx
- src/components/layout/drawer/Extras.jsx
- src/components/layout/drawer/SelectorList.jsx
- src/services/functions/hasAll.js
- Removes the need for the `map.misc.enableConfirmedInvasions` by checking for the existence of any confirmed invasions in the incident table
- Removes the `map.misc.enableQuestSetSelector`, this is just always enabled now. 
- Combines Kecleon with showcase options in the quick select section under `Event Stops`. This is for consistency sake, don't need two levels of menus
- Includes some refactors to how the options on the left of the adv menu look as well as more consistent icons for reset actions
- Also resolves #935
> Refine available checks

- server/src/configs/default.json
It seems that the old link does not navigate to the coordinates anymore. It should work with the new URL.
> Fix Google Map Link

- .github/workflows/config.yml
- .github/workflows/docker.yml
- .github/workflows/lint.yml
- .github/workflows/locales.yml
- .github/workflows/main.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .github/workflows/sentry.yml
- packages/config/lib/scripts/genEnvConfig.js
Make the CI actions a bit more consistent and less messy
> fix: refine ci

- packages/locales/lib/human/en.json
- packages/types/lib/server.d.ts
- server/src/configs/default.json
- server/src/models/Pokemon.js
- server/src/services/DbCheck.js
- server/src/services/config.js
- src/components/Config.jsx
- src/components/layout/dialogs/search/renderOption.jsx
- src/components/layout/drawer/Settings.jsx
- src/components/popups/Route.jsx
- src/hooks/useFormatDistance.js
- src/hooks/useStorage.js
- src/services/functions/formatDistance.js
Moves the distance selection to the client for more consistency and there's not really any reason why this calculation should be forced to be the same for all users. 
`map.misc.distanceUnit` was previously `km/mi` and is now `kilometers/miles`, an inline migration was added to change it at startup with a warning log. 
Resolves #865
> refactor: move distance unit to client

- docker-compose.example.yml
As it's not used for docker users if they don't add it manually.
Untested yet
> Add server cache to docker example

- packages/locales/lib/human/en.json
- packages/locales/lib/index.js
- packages/locales/lib/missing.js
- packages/locales/lib/utils.js
- server/src/graphql/resolvers.js
- server/src/graphql/typeDefs/index.graphql
- server/src/graphql/typeDefs/map.graphql
- server/src/index.js
- server/src/routes/clientRouter.js
- src/assets/css/main.css
- src/components/virtual/Table.jsx
- src/pages/index.jsx
- src/pages/locales/components/AllSwitch.jsx
- src/pages/locales/components/EditLocale.jsx
- src/pages/locales/components/LocalesFooter.jsx
- src/pages/locales/components/LocalesHeader.jsx
- src/pages/locales/components/LocalesTable.jsx
- src/pages/locales/hooks/store.js
- src/pages/locales/index.jsx
- src/services/queries/config.js
- src/utils/downloadJson.js
This adds a `/locales` editing page to try and make it easier to view and submit missing locales.
> feat: locales editing page

- src/pages/Blocked.jsx
This PR simply adds a button to link to the URL users have set in their config for `rolesLink` with the button text to be `rolesLinkName`.
Default color is `success` and also is set to open in a new tab.
> Add RoleLink info to Blocked page

- src/features/webhooks/human/Location.jsx
- src/hooks/useLocation.js
- src/pages/map/components/FloatingBtn.jsx
- src/pages/map/components/Layers.jsx
It seems the translating API was changed when the version of Leaflet Locate Control was updated. This fixes the translations and also now respects the users choice of Miles (feet) or Kilometers (meters). Also fixes some React re-rendering issues and generally makes things more consistent.
> fix: locate translations / unit of measurement

- src/features/webhooks/human/area/AreaGroup.jsx
Remove container from AreaGroups, so in case you have Parent area(s) which doesn't fill out the entire Webhook popup width, then it align with the rest of them.
Before:
After:
> Remove flex container behavior from AreaGroups

- src/pages/map/components/FloatingBtn.jsx
Just simply color the icon when using customFloatingIcons to white, so they match the other icons while using light mode.
Light mode (Changed to white now):
Dark mode:
> Allign customFloatingIcons icon color with the rest of the icons.

- packages/locales/lib/human/de.json
- packages/locales/lib/human/en.json
- packages/locales/lib/human/es.json
- packages/locales/lib/human/fr.json
- packages/locales/lib/human/pl.json
- server/src/configs/custom-environment-variables.json
- server/src/configs/default.json
- server/src/models/Pokestop.js
- server/src/services/EventManager.js
- server/src/services/filters/builder/base.js
- src/features/drawer/pokestops/Invasions.jsx
Adds 2 toggles to further filter Rocket Pokemon: `Exclude Rocket Leaders` & `Exclude Rocket Grunts`.
It should be noted that I've only tested this with a limited data setup (actually just 2 pokestops, one with character ID 16, and one with character ID 41), so it could use a test with a larger set of data. I don't have a scanner set up so I'm unable to do this
> [Feature Request]: Exclude rocket grunt toggle & exclude rocket leader toggle

- packages/locales/lib/human/en.json
- src/features/drawer/pokemon/ModeSelector.jsx
- src/features/s2cell/GenerateCells.jsx
This relates the current zoom level that the user is at to which S2 cells are able to be rendered, preventing users from loading too many cells and locking up their map. 
E.g.
- User has L10, L15, and L20 cells enabled
- At zoom level 9 or lower, nothing will render
- At zoom level 10, only the L10 cells will render
- At zoom level 15, both 10 and 15 will render, etc
> fix: prevent users from loading too many s2 cells

- server/src/models/Pokestop.js
- src/components/filters/QuestConditions.jsx
- src/features/drawer/pokestops/Quests.jsx
- src/hooks/useMapData.js
This fixes an issue that appeared when a specific quest reward has two quest conditions that have the same quest title but different target amounts. Since this changes the format of the filter it also includes a migration to fix any existing filtering that users are doing by quest conditions at startup.
> fix: quest conditions with similar quest titles

- index.html
- public/loading.js
This moves the loading script that selects locales before i18n is initialized to an external file to follow new security policies.
> fix: move loading locales script to external script file

- server/src/configs/default.json
- server/src/index.js
- server/src/services/functions/reloadConfig.js
Add configurable value to opt in to using the `helmet` middleware or not. Disabled by default since the middleware is more disruptive than originally realized.
> fix: helmet middleware opt in

- config/default.json
- package.json
- server/src/filters/builder/base.js
- server/src/models/Nest.js
- server/src/services/DbCheck.js
- server/src/ui/primary.js
- server/src/utils/reloadConfig.js
- src/components/inputs/MultiSelector.jsx
- src/features/drawer/S2Cells.jsx
- src/features/drawer/components/Section.jsx
- src/features/drawer/nests/ActiveNests.jsx
- src/features/drawer/nests/AvgSlider.jsx
- src/features/drawer/nests/index.jsx
- src/features/nest/NestPopup.jsx
- src/features/nest/NestTile.jsx
- src/pages/map/components/Layers.jsx
- Adds a selector to view `inactive` / `active` / `all` nests
- Necessary code to account for nests in the client not having a valid pokemon_id 
- Makes the nest polygons clickable / have a popup too
- Config value comparison on hot reload for undefined values
- Query debug logging
> feat: more nest viewing options

- .github/workflows/docker.yml
the condition blocked writing gitsha and gitref to file on PRs
I checked the PR images, all of them contained empty `.gitsha` and `.gitref` files :) 
To-do:
This writes `refs/pull/1068/merge` into .gitref... We might need to change the flow a bit
> chore: fix docker image steps

- server/src/services/DbManager.js
> fix: no more search hard limits

- config/default.json
- packages/locales/lib/human/en.json
- packages/types/lib/scanner.d.ts
- packages/types/lib/server.d.ts
- server/src/filters/builder/base.js
- server/src/graphql/typeDefs/scanner.graphql
- server/src/models/Station.js
- server/src/services/DbManager.js
- server/src/ui/drawer.js
- src/features/station/StationPopup.jsx
- src/features/station/useStationMarker.js
- src/pages/map/hooks/usePermCheck.js
- src/services/queries/index.js
- src/services/queries/station.js
No longer ~~Requires https://github.com/UnownHash/Golbat/pull/240~~. Needs help testing.
> feat: support for total_stationed_gmax

- README.md
We should have updated this a year ago, I guess, to mention Fletchling :) Probably not worthwhile to mention nestwatcher, anymore, so I just replaced it.
> Update README for Fletchling

- config/default.json
The default url for Waze works fine IIRC when you are not using CarPlay. The Waze app will open to the location and allow you to start navigation.
However, if you have CarPlay, the Waze app just opens to the default 'menu', and doesn't seem to know anything about the location.
This has always worked fine from Poracle notifications. So this adds a couple of extra query params that Poracle uses. This fixes it.
> Fix Waze url for navigation when using CarPlay

- packages/config/lib/mutations.js
- packages/types/lib/config.d.ts
Minor change to make it a little better to handle lots of Discord permissions in the local.json file.
Previously we would have to define roles like this:
```json
"aliases": [
{
"role": "123",
"name": "supporter-bronze"
},
{
"role": "456",
"name": "supporter-silver"
},
{
"role": "789",
"name": "supporter-gold"
}
```
Now we can use an array to define a group of roles like this:
```json
"aliases": [
{
"role": ["123", "456", "789"],
"name": "supporter"
}
```
This makes permissions easier to read and handle, especially with many roles across different servers:
```json
"perms": {
"iv": {
"enabled": true,
"trialPeriodEligible": false,
"roles": ["supporter"]
}
```
Tested on my own production instance.
> feat: add role array support

- server/src/routes/rootRouter.js
- src/features/profile/ExtraFields.jsx
- src/features/profile/index.jsx
- src/services/fetches.js
These fields in profile (configured in config: database.settings.extraUserFields) refresh on re-login only. I made them update on each profile window open
Disclaimer: PR created with AI. I have no idea what I'm doing
> Faster extraUserFields
